import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ASSET_DIR = path.join(__dirname, '../public/Sept12assets/sep12');
const OUTPUT_FILE = path.join(__dirname, '../src/game/assetData.js');

const CSV_FILES = [
    '3_Members.csv', // Buildings, palms
    '5_Members.csv', // Men, Terrorists
    '6_Members.csv', // Women
    '8_Members.csv', // Kids
    '9_Members.csv', // Dogs
];

const assetData = {};

function parseCSV(filename) {
    const content = fs.readFileSync(path.join(ASSET_DIR, filename), 'utf8');
    const lines = content.split('\n'); // handle CR?

    // Skip header
    for (let i = 1; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;

        // Parse line: Number,Type,Name,Registration Point,Filename
        // Regex to handle quoted fields containing commas
        const parts = line.match(/(".*?"|[^",\s]+)(?=\s*,|\s*$)/g);

        if (!parts || parts.length < 4) continue;

        const id = parts[0].replace(/"/g, ''); // Number
        const type = parts[1].replace(/"/g, ''); // Type
        const name = parts[2].replace(/"/g, ''); // Name
        const regPointRaw = parts[3].replace(/"/g, '').replace(/[() ]/g, ''); // Registration Point (x,y)

        if (type !== 'bitmap') continue;

        const [regX, regY] = regPointRaw.split(',').map(Number);
        const prefix = filename.split('_')[0]; // e.g. "3" from "3_Members.csv"

        // Construct unique ID key: "3_206"
        const uniqueId = `${prefix}_${id}`;

        // Filename in folder is usually "prefix_id.png"
        // Check if file exists, sometimes it might be .jpg or .swf (ignored)
        const imageFilename = `${uniqueId}.png`;

        if (fs.existsSync(path.join(ASSET_DIR, imageFilename))) {
            assetData[uniqueId] = {
                id: uniqueId,
                name: name,
                src: `/Sept12assets/sep12/${imageFilename}`,
                regX: regX,
                regY: regY
            };
        }
    }
}

CSV_FILES.forEach(file => {
    try {
        console.log(`Processing ${file}...`);
        parseCSV(file);
    } catch (e) {
        console.error(`Error processing ${file}:`, e.message);
    }
});

const fileContent = `/**
 * Auto-generated asset metadata from Original Game CSVs
 * Generated by scripts/generateAssetData.js
 */
export const ASSETS = ${JSON.stringify(assetData, null, 2)};
`;

fs.writeFileSync(OUTPUT_FILE, fileContent);
console.log(`Generated ${OUTPUT_FILE} with ${Object.keys(assetData).length} assets.`);
