// Comprehensive Emoji Data with English and Spanish search keywords
export const EMOJI_DATA = {
    // Smileys & Emotion
    '😀': 'grinning face happy smile sonreir feliz risa alegre',
    '😃': 'grinning big eyes happy joy sonreir ojos abiertos feliz contento',
    '😄': 'grinning smiling eyes happy laugh risa ojos contentos feliz carcajada',
    '😁': 'beaming smiling grin happy dientes sonrisa feliz',
    '😆': 'laughing squinting closed eyes haha risa a carcajadas riendo divertido',
    '😅': 'sweat smile nervous relief sudor alivio sonrisa nerviosa',
    '🤣': 'rolling on floor laughing rofl haha me muero de risa rodando',
    '😂': 'tears of joy laughing cry haha lagrimas de risa llorando risa chiste',
    '🙂': 'slightly smiling face smile simple feliz leve contento',
    '🙃': 'upside down silly sarcasm al reves tonto ironia loco',
    '😉': 'winking face wink flirt guiño ojo coqueto picaro complicidad',
    '😊': 'smiling blushing warm happy sonriente sonrojo tierno feliz tierno',
    '😇': 'halo innocent angel cherub angel celestial inocente santo bondad',
    '🥰': 'smiling hearts love adore enamorado corazones amor tierno te quiero',
    '😍': 'heart eyes love crush enamorado ojos corazon me encanta amor',
    '🤩': 'star struck excited amazed deslumbrado estrellas wow emocionado brillante',
    '😘': 'kiss blowing heart love beso besito amor cariño mua',
    '😗': 'kissing face kiss beso trompita silbando',
    '😚': 'kissing closed eyes love blush beso ojos cerrados cariño',
    '😋': 'yum delicious food taste licking rico delicioso sabroso lengua rico',
    '😛': 'tongue out silly joke lengua fuera broma payaso sacando la lengua',
    '😜': 'winking tongue playful crazy guiño lengua loco chiste broma',
    '🤪': 'zany face crazy wild goofy loco demente alocado chiflado mareado',
    '😝': 'squinting tongue gross haha lengua ojos apretados asco broma juego',
    '🤑': 'money mouth rich cash dollar dinero plata rico billete dolar oro',
    '🤗': 'hugging face hug warmth abrazo abrazar cariñoso cariños',
    '🤭': 'hand over mouth oops giggle tapandose boca risita travieso ups secreto',
    '🤫': 'shushing face quiet silence secret silencio shh secreto callar callate silencio',
    '🤔': 'thinking face think wonder hmm pensativo pensando duda hmmm pensar idea',
    '🤐': 'zipper mouth secret shut up boca cremallera silencio cerrado mudo',
    '🤨': 'raised eyebrow suspicious skeptical ceja levantada sospecha duda desconfianza',
    '😐': 'neutral face meh expressionless cara neutral indiferente serio poker',
    '😑': 'expressionless face blank bored inexpresivo aburrido plano sin expresion',
    '😶': 'mouthless face speechless silent sin boca sin palabras mudo callado',
    '😏': 'smirking sly confident flirt picara sonrisa canchero presumido picaro',
    '😒': 'unamused bored annoyed disgust descontento molesto que fastidio fastidio desanimo',
    '🙄': 'rolling eyes annoyed whatever rodando ojos fastidio otra vez desden',
    '😬': 'grimacing awkward yikes mueca incomodo dientes tirante verguenza',
    '🤥': 'lying face pinochio long nose mentiroso pinocho nariz larga mentira bola',
    '😌': 'relieved peace calm zen aliviado paz tranquilidad sereno relax',
    '😔': 'pensive sad depressed down triste pensativo decaido cabizbajo nostalgia',
    '😪': 'sleepy tired drool tear adormilado cansado gota sueño cansancio',
    '🤤': 'drooling saliva hungry sleep babeando baba sabroso hambriento que rico',
    '😴': 'sleeping face zzz snore sleep durmiendo dormido sueño roncar cama zzz',
    '😷': 'mask medical sick doctor virus barbijo mascarilla enfermo tapabocas barbijo',
    '🤒': 'thermometer fever sick ill termometro fiebre enfermo gripe temperatura',
    '🤕': 'head bandage injured hurt vendaje cabeza herido lesion golpe venda',
    '🤢': 'nauseated sick vomit disgust nausea verde asco descompuesto repugnante',
    '🤮': 'vomiting barf sick gross vomit vomitando vomito asco guacala',
    '🤧': 'sneezing tissue sick allergy estornudo pañuelo resfriado alergia gripe',
    '🥵': 'hot red sweat heat warm calor rojo transpirado acalorado ardiente fuego bochorno',
    '🥶': 'cold blue freezing ice frow friolento azul helado congelado temblando frio nieve',
    '🥴': 'woozy drunk dizzy groggy mareado borracho confundido torcido ebrio',
    '😵': 'dizzy dead eyes knockout aturdido mareado inconsciente ojos cruzados mareo',
    '🤯': 'exploding head mind blown shock cabeza explotando increible bomba boom mente flipar',
    '🤠': 'cowboy hat sheriff western vaquero sombrero comisario oeste texas',
    '🥳': 'party celebration confetti horn fiesta festejando gorrito cumpleano festejo party',
    '😎': 'cool sunglasses badass stylish gafas de sol lentes canchero facha gafas chulo',
    '🤓': 'nerd glasses smart geek empollon gafas friki inteligente nerd inteligente',
    '🧐': 'monocle classy inspecting detective monocolo elegante curioso observador',
    '😕': 'confused uncertain puzzled confundido desorientado desconcertado que',
    '😟': 'worried nervous anxious preocupado inquieto intranquilo temor',
    '🙁': 'slightly frowning sad triste apenado desconforme ceño bajon',
    '😮': 'open mouth surprise gasp boca abierta sorprendido wow asombro que',
    '😯': 'hushed surprised silent callado asombrado oh impacto',
    '😲': 'astonished amazed shocked asombrado atonito increible pasmado',
    '😳': 'flushed embarrassed red blush sonrojado avergonzado pavor pena rojo',
    '🥺': 'pleading begging cute puppy eyes suplicante ojitos tierno por favor ruega ruego',
    '😦': 'frowning open mouth distress asustado boca abierta que paso susto',
    '😧': 'anguished hurt shock angustiado disgustado consternado agonia',
    '😨': 'fearful scared nervous temeroso asustado miedo panico susto',
    '😰': 'anxious sweat scared worry ansioso sudor frio panico miedo angustia',
    '😥': 'sad relieved disappointed decepcionado triste alivio suspiro uff',
    '😢': 'crying tear sad weeping llorando lagrima triste llanto pena dolor',
    '😭': 'loudly crying sob bawling weeping llanto desgarrador llorando a mares triste llanto sollozo',
    '😱': 'screaming fear shock terror gritando grito horror panico miedo munck susto alarido',
    '😖': 'confounded tight eyes distressed desesperado disgusto frustrado rabia',
    '😣': 'persevering struggle pain aguantando esfuerzo dolor sufrimiento resistir',
    '😞': 'disappointed sad gloomy down decepcionado desanimado triste bajon desilusion',
    '😓': 'downcast sweat struggle tired sudor cansancio que alivio o no gota',
    '😩': 'weary tired exhausted exasperated agotado que cansancio rendido agotamiento',
    '😫': 'tired face whining groan cansado exhausto protestando fatiga',
    '🥱': 'yawning tired sleepy bored bostezando sueño bostezo aburrimiento flojera',
    '😤': 'triumph steam angry snort furioso bufando vapor orgullo rabia resoplar',
    '😡': 'pouting rage red angry enojado furia rojo rabia caliente furioso enojo',
    '😠': 'angry face mad annoyance enfadado molesto bronca enojado enojo enfado',
    '🤬': 'cursing swear swearing angry malas palabras insulto censura furioso enojo palabrotas',
    '💀': 'skull skeleton dead death calavera esqueleto muerte muerto fin hueso calaverita mori',
    '☠️': 'crossbones skull poison danger calavera pirata veneno peligro muerte huesos bandera',
    '💩': 'poop shit pile caca mierda popo bosta gracioso caca mojón',
    '🤡': 'clown circus joker payaso circo bromista comico it bufón',
    '👻': 'ghost spooky boo halloween fantasma susto espiritu fantasmita miedo',
    '👽': 'alien extraterrestrial ufo ovni marciano nave espacial extraterrestre alienigena',
    '👾': 'space invader pixel alien game videojuego monstruo retro arcade pixelart marcianito',
    '🤖': 'robot android tech ai robot automata inteligencia artificial tecnologia bot meca',
    '😺': 'cat grinning smile gatito gato sonriendo miau felino',
    '😸': 'cat grinning smiling eyes gato riendo contento risueño',
    '😹': 'cat tears joy laugh gato llorando de risa risas carcajada',
    '😻': 'cat heart eyes love gato enamorado ojos corazones amor te quiero',
    '🔥': 'fire flame lit hot blaze fuego llama caliente calor quemar fuego fogata lumbre candela',
    '✨': 'sparkles shine magic clean glitter brillos estrellas magia magico destellos chispas resplandor',
    '⭐': 'star yellow favorite review rating estrella amarillo favorito calificacion premio astro',
    '🌟': 'glowing star shine bright radiant estrella brillante resplandor destello resplandeciente',
    '💥': 'boom explosion collision burst colision choque explosion estallido pow pum trancazo golpe',

    // People, Gestures & Hearts
    '👋': 'wave waving hand hello goodbye mano saludando hola chau adios saludo despedida',
    '🤚': 'raised back hand stop dorso mano levantar detener parar palma',
    '🖐️': 'fingers splayed five palm mano dedos abiertos cinco palma alto parar',
    '✋': 'raised hand high five stop mano alzada alto parar choca los cinco mano levantada detener',
    '🖖': 'vulcan salute spock star trek saludo vulcano prosperidad paz',
    '👌': 'ok okay hand perfect excellent mano ok perfecto bien genial de acuerdo aprobado',
    '🤌': 'pinched fingers italian what mano pinzada italiano que dices gesto que onda italia',
    '🤏': 'pinching hand little small bit pellizco poquito chiquito poco pizca pequeño',
    '✌️': 'peace victory two fingers v paz victoria dos dedos calma amor y paz',
    '🤞': 'crossed fingers luck hope cruzando dedos suerte ojala esperanza dedos cruzados',
    '🤟': 'love you gesture rock te amo señas afecto cariño te quiero lenguaje de señas',
    '🤘': 'rock on horns metal heavy rock and roll cuernos recital musica heavy metal',
    '🤙': 'call me shaka hang loose llamame onda surfer surf llamada shaka relax',
    '👈': 'finger point left señalar izquierda mira alla dedo señalando a la izquierda',
    '👉': 'finger point right señalar derecha mira aqui dedo señalando a la derecha',
    '👆': 'finger point up arriba señalar techo dedo apuntando arriba',
    '👇': 'finger point down abajo señalar suelo piso dedo apuntando abajo',
    '☝️': 'index pointing up one attention dedo arriba uno atencion primero indice',
    '👍': 'thumbs up good like approve pulgar arriba me gusta bien aprobado pulgares ok pulgarcito genial',
    '👎': 'thumbs down bad dislike no pulgar abajo desaprueba mal pulgares no me gusta desaprobado',
    '✊': 'fist raised punch power puño cerrado fuerza lucha poder golpe resistencia',
    '👊': 'fist oncoming punch brofist puñetazo choque de puños golpe pelea piña combo',
    '🤛': 'fist left facing bump puño izquierda choque puñetazo',
    '🤜': 'fist right facing bump puño derecha choque puñetazo',
    '👏': 'clapping hands applause bravo aplausos aplaudir felicitaciones palmas palmadas aplauso',
    '🙌': 'raising hands celebration praise celebrar manos arriba alabanza hurra aleluya festejo',
    '👐': 'open hands hug palms manos abiertas ofrenda recibir abrazo apertura',
    '🤲': 'palms together prayer request rezar pedir manos unidas ofrenda suplica rezo',
    '🤝': 'handshake agreement deal partner apreton de manos trato acuerdo socios estrechar mano negocio',
    '🙏': 'folded hands please pray thank you rezar oracion por favor gracias namaste agradecido pedir disculpas',
    '✍️': 'writing hand pen signing escribir mano lapiz firma redactar caligrafia firmar',
    '💪': 'biceps muscle strong fitness power fuerza musculo entrenar brazo fuerte poder gym gimnasio musculos',
    '🧠': 'brain mind intellect think smart cerebro mente inteligente pensar inteligencia memoria saber sesos',
    '👀': 'eyes looking look watching gaze ojos mirando mirar curioso espiar ver mirada atenta',
    '👁️': 'eye seeing view watch ojo mirar vision iris vista ver mirada',
    '👅': 'tongue taste lick mouth lengua saborear lamer gusto sacar la lengua probar',
    '👄': 'lips mouth kiss seductive boca labios besar sensual beso labial sonrisa',
    '💋': 'kiss mark lipstick love lips beso marca de labial labios amor carmin beso carmin',
    '❤️': 'red heart love passion corazon rojo amor pasion cariño romantic enamorados afecto te amo',
    '🧡': 'orange heart love warmth corazon naranja amor calidez ternura',
    '💛': 'yellow heart friendship happiness corazon amarillo amistad alegria cariño',
    '💚': 'green heart nature jealous health corazon verde naturaleza esperanza vida salud ecologia',
    '💙': 'blue heart trust peace cool corazon azul confianza calma lealtad frio tranquilidad',
    '💜': 'purple heart royalty magic luxury corazon morado violeta magia realeza misterio purpura',
    '🖤': 'black heart dark gothic sorrow corazon negro luto dolor oscuro pena elegancia',
    '🤍': 'white heart pure peace angel corazon blanco pureza paz sincero claridad bondad',
    '🤎': 'brown heart earth chocolate corazon marron cafe chocolate tierra calidez',
    '💔': 'broken heart sadness break heartbreak corazon roto desamor tristeza ruptura pena dolor llanto',
    '❣️': 'heart exclamation love punctuation corazon exclamacion signo amor corazon con punto',
    '💕': 'two hearts floating love pink dos corazones flotando amor ternura enamorados pareja',
    '💞': 'revolving hearts revolving love corazones girando orbitando amor mareo de amor',
    '💓': 'beating heart pulse love latiendo corazon latido ritmo amor palpitando',
    '💗': 'growing heart expanding love corazon creciente aumentando amor emocion',
    '💖': 'sparkling heart love glitter shiny corazon con brillos destellante amor brillitos',
    '💘': 'cupid heart arrow love fall cupido flecha corazon flechazo amor enamorarse flecha de cupido',
    '💝': 'heart ribbon gift love present corazon regalo cinta presente amor moño obsequio',
    '🎉': 'party popper confetti celebrate fiesta cotillon serpentina festejo cumple party año nuevo celebracion',
    '🎊': 'confetti ball celebration fiesta bola confeti lluvia festejo celebracion evento',
    '🎈': 'balloon red party celebration globo fiesta cumple rojo inflable globito cumpleaños',
    '🏆': 'trophy cup winner champion prize trofeo copa campeon ganador premio primer lugar victoria triunfo copa de oro',
    '👑': 'crown king queen royal gold corona rey reina realeza nobleza oro monarca reina emperador',

    // Crates & Mystery Boxes (Algebra)
    '📦x': 'crate x mystery variable algebra box cajon incognita caja variable incógnita misterio contenedor equis x valor incognito',
    '📦': 'crate package box parcel shipping delivery caja paquete cajon carton envio entrega embalaje encomienda',
    '📦?': 'crate question mystery box secret caja pregunta misterio incognita duda secreto interrogacion signo caja secreta',
    '🧰': 'toolbox tools kit repair craft caja de herramientas taller arreglo arreglar mecanica herramientas martillo llave',
    '🧱': 'brick wall build construction building ladrillo pared muro construccion obra albañil bloques pared',
    '🪵': 'wood log timber lumber campfire leña tronco madera madero bosque fogata trozo palo',
    '🧺': 'basket picnic laundry wicker canasta cesta picnic canasto mimbre ropa canastita',
    '💼': 'briefcase business work lawyer portfolio maletin portafolios trabajo oficina ejecutivo negocio valija maletin',
    '🪨': 'rock stone pebble boulder hard roca piedra pedrusco canto rodado mineral peña duro',
    '💎': 'diamond gem crystal jewelry treasure diamante gema joya brillante cristal tesoro piedra preciosa zafiro rubi',
    '🪙': 'coin money gold silver currency token moneda plata oro dinero metal sueldo cambio centavo valor',
    '🧪': 'test tube science chemistry experiment lab tubo de ensayo ciencia quimica laboratorio experimento probeta pocion liquido',
    '⚗️': 'alembic alchemy chemistry science potion alambique alquimia quimica destilacion pocion experimento matraz',
    '🔮': 'crystal ball fortune fortune teller magic future bola de cristal magia adivino futuro hechicero clarividencia suerte',
    '🏺': 'amphora vase jar ancient pottery vasija anfora jarron ceramica antiguedad urna reliquia florero',
    '🗝️': 'old key secret antique unlock llaves llave antigua abrir secreto candado misterio cerradura llavecita',
    '💰': 'money bag dollars riches wealth cash bolsa de dinero saco plata dolares fortuna riqueza billetes oro plata',
    '🏅': 'medal sports award honor ribbon medalla premio deporte condecoracion cinta medalla de oro',
    '🎖️': 'military medal military honor decoration medalla militar honor condecoracion merito emblema insignia',

    // Fruits, Vegetables & Food
    '🍎': 'red apple fruit healthy food fruit manzana roja fruta comida rica saludable postre arbol',
    '🍏': 'green apple fruit sour food manzana verde fruta acida rica saludable manzana',
    '🍐': 'pear fruit sweet healthy pera fruta rica dulce verde arbol peral',
    '🍊': 'tangerine orange mandarin citrus fruit mandarina naranja citrico fruta vitamina c gajos jugo',
    '🍋': 'lemon sour citrus yellow fruit limon acido citrico amarillo fruta limonada agrio',
    '🍌': 'banana fruit monkey yellow potassium platano banana fruta mono potasio amarillo selva cambur',
    '🍉': 'watermelon summer red fruit slice sandia fruta fresca verano roja tajada pepitas melon de agua',
    '🍇': 'grapes wine purple fruit bunch uvas racimo fruta morada vino vid parra racimo de uvas',
    '🍓': 'strawberry berry red sweet fruit frutilla fresa fruta roja dulce postre frutillita frutillas',
    '🫐': 'blueberries berry fruit antioxidants arandano arandanos mora fruta azul antioxidante moras frutos rojos',
    '🍈': 'melon honeydew fruit cantaloupe melon dulce fruta fresca verde tajada',
    '🍒': 'cherries cherry red twin fruit cerezas guindas fruta roja dulce par cereza picota',
    '🍑': 'peach fruit juicy sweet melocoton durazno fruta dulce jugosa piel de durazno',
    '🥭': 'mango tropical fruit sweet mango fruta tropical dulce exquisito pulpa',
    '🍍': 'pineapple tropical fruit sweet piña anana fruta tropical dulce hojas corona',
    '🥥': 'coconut tropical nut milk beach coco fruta tropical leche palmera playa agua de coco',
    '🥝': 'kiwi fruit fuzzy green slice kiwi fruta verde fresca acida semillas',
    '🥑': 'avocado guacamole healthy green fruit aguacate palta fruta verde ensalada guacamole carozo',
    '🍆': 'eggplant aubergine vegetable berenjena verdura vegetal morado ensalada',
    '🥕': 'carrot vegetable orange healthy rabbit zanahoria verdura conejo vegetal naranja ensalada vianda',
    '🌽': 'corn maize cob vegetable harvest maiz choclo elote mazorca vegetal cereal grano espiga',
    '🥒': 'cucumber pickle salad vegetable pepino ensalada vegetal verde fresco pepinillo rodajas',
    '🥦': 'broccoli vegetable healthy green trees brocoli verdura arbolito vegetal verde sano saludable',
    '🧄': 'garlic bulb cook spice season ajo diente de ajo verdura condimento cocina sabor olor',
    '🧅': 'onion cook spice salad bulb cebolla verdura vegetal cocina llorar morada blanca sofrito',
    '🍄': 'mushroom fungus toadstool toad champiñon hongo seta boletus bosque hongo silvestre',
    '🥜': 'peanuts peanut nut snack shell mani cacahuate frutos secos cascara aperitivo',
    '🌰': 'chestnut nut acorn autumn castaña fruto seco nuez otoño bosque castaño',
    '🍞': 'bread loaf bakery toast pan hogaza panaderia tostada harina molde baguette rebanada',
    '🥐': 'croissant pastry french butter croissant medialuna bolleria manteca panaderia factura medialunas',
    '🥖': 'baguette french bread loaf baguette pan frances flauta panaderia barra',
    '🥨': 'pretzel snack salt bakery pretzel lazo snack salado aleman panecillo',
    '🥞': 'pancakes breakfast syrup hotcakes panqueques hot cakes desayuno miel torre tortitas miel',
    '🧇': 'waffle breakfast syrup grid waffle gofre desayuno merienda cuadrícula dulce',
    '🧀': 'cheese dairy yellow hole swiss queso triangulo lacteo comida raton gruyere parmesano',
    '🍖': 'meat on bone roast ham carve carne con hueso asado chuleta presa costilla bife',
    '🍗': 'poultry leg chicken drumstick roast pata de pollo presa pollo frito muslo asado presa',
    '🥩': 'cut of meat steak beef raw bife carne asado corte churrasco filete bife chorizo lomo',
    '🥓': 'bacon pork breakfast crisps panceta tocino desayuno frito tiras crujiente chancho',
    '🍔': 'hamburger burger fast food beef patty hamburguesa comida rapida carne sandwich con queso burger',
    '🍟': 'french fries chips fast food potato papas fritas patatas fritas cono comida rapida guarnicion papitas',
    '🍕': 'pizza slice cheese pepperoni fast food pizza porcion porcion de pizza queso comida muzarella pepperoni',
    '🌭': 'hot dog sausage mustard fast food pancho perrito caliente hotdog salchicha mostaza completo',
    '🥪': 'sandwich lunch bread snack emparedado sandwich tostado queso jamon emparedado merienda',
    '🌮': 'taco mexican street food corn taco comida mexicana tortilla carne al pastor maiz salsa',
    '🌯': 'burrito wrap mexican wrap burrito comida mexicana envoltorio fajita frijoles carne',
    '🫔': 'tamale mexican corn husk tamal comida tradicional chala masa relleno',
    '🥗': 'green salad healthy vegetables bowl ensalada verde vegetales comida sana saludable lechuga tomate bowl',
    '🍲': 'pot of food stew soup hearty olla guiso sopa comida casera puchero cazuela estofado',
    '🍜': 'steaming bowl ramen noodles soup bowl fideos ramen sopa fideos asiatico palillos caldo tallarines',
    '🍝': 'spaghetti pasta italian noodles sauce espaguetis pasta salsa fideos plato bolognesa tallarines',
    '🍠': 'roasted sweet potato yam batata boniato camote asado dulce papa dulce',
    '🍣': 'sushi nigiri japanese fish rice sushi salmon arroz comida japonesa rollo maki sashimi',
    '🍤': 'fried shrimp prawn tempura camarón frito gamba langostino rebozado tempura frito',
    '🍦': 'ice cream soft serve cone dairy helado cucurucho cono crema postre heladeria nieve',
    '🍧': 'shaved ice dessert sweet cup granizado raspado hielo postre dulce vaso sabor jarabe',
    '🍨': 'ice cream cup dessert bowl helado copa pote postre dulce bocha helado de vainilla',
    '🍩': 'doughnut donut sweet dessert ring dona rosquilla postre dulce glaseado rosquita rosquilla',
    '🍪': 'cookie chocolate chip biscuit galleta galletita chocolate chip dulce merienda oreo horneada',
    '🎂': 'birthday cake dessert celebration torta pastel de cumpleaños fiesta vela festejo tarta cumpleaños',
    '🍰': 'shortcake slice cake dessert sweet porcion de torta pastel postre porcion tarta dulce rebanada',
    '🧁': 'cupcake muffin icing dessert pastelito cupcake muffin crema dulce magdalena copete',
    '🥧': 'pie tart bake pastry tarta pastel relleno pay horno dulce manzana tarta dulce',
    '🍫': 'chocolate bar candy sweet cocoa chocolate tableta barra golosina dulce cacao tableta chocolate',
    '🍬': 'candy sweet confection sweet caramel caramelo dulce golosina envoltorio azucar confite',
    '🍭': 'lollipop sweet candy sucker chupetin paleta piruleta dulce caramelo golosina',
    '🍮': 'custard pudding flan dessert flan postre crema caramelo flancito postre dulce',
    '🍯': 'honey pot sweet bee nectar miel jarro de miel pote dulce abeja panal tarro de miel',
    '🍿': 'popcorn movie cinema snack pochoclo palomitas maiz cine pelicula snack pororo cabritas pop',
    '☕': 'hot beverage coffee tea mug cafe taza cafe humeante caliente merienda desayuno espresso cafecito',
    '🍵': 'teacup teacup matcha green tea taza de te te verde matcha infusion caliente sorbo',
    '🧃': 'beverage box juice straw box jugo cajita jugo con bombilla merienda pajita zuma carton',
    '🥤': 'cup with straw soda soft drink vaso con sorbete gaseosa refresco vaso plastico pajita coca cola bebida',

    // Animals & Wildlife
    '🐶': 'dog puppy pet animal friend perro perrito cachorro mascota canino can pichicho ladrar',
    '🐱': 'cat kitten pet animal meow gato gatito mascota felino miau michi felino minino',
    '🐭': 'mouse rodent cheese animal raton ratoncito roedor queso orejas laucha mikey',
    '🐹': 'hamster rodent pet cheeks animal hamster roedor mascota cachetes cuya cobayo',
    '🐰': 'rabbit bunny easter pet ears conejo conejito mascota pascuas orejas saltar liebre',
    '🦊': 'fox clever wild forest animal zorro zorrito astuto bosque animal cola peluda',
    '🐻': 'bear wild forest teddy animal oso osito pardo bosque peluche grizzly oso polar',
    '🐼': 'panda bear bamboo china animal oso panda panda bambu tierno blanco negro oso',
    '🐨': 'koala australia eucalyptus bear animal koala oso australia eucalipto arbol marsupial',
    '🐯': 'tiger wild big cat stripes animal tigre felino rayas selva rugido bengala carnívoro',
    '🦁': 'lion king safari roar predator leon melena safari rey de la selva felino rugido melenudo',
    '🐮': 'cow farm dairy cattle moo animal vaca vaquita ternera leche granja mu ganado lechera',
    '🐷': 'pig farm pork oink snout animal cerdo chanchito puerco granja hocico cochino marrano',
    '🐸': 'frog toad green amphibian pond rana sapo anfibio verde laguna croac charco sapito',
    '🐵': 'monkey ape banana primate animal mono changuito primate selva monito chimpance chistoso',
    '🐔': 'chicken hen farm fowl cluck gallina pollo granja ave plumas cacareo gallo granja',
    '🐧': 'penguin antarctica cold bird tux pinguino polo antartida ave nieve frio traje pinguinito',
    '🐦': 'bird blue bird fly tweet animal pajaro pajarito ave volar trinar plumas canto nido',
    '🐥': 'front-facing baby chick yellow bird pollito pollo pichon bebe amarillo ave pollito piando',
    '🦆': 'duck pond water bird quack pato ave laguna plumaje cuak graznido patito lago',
    '🦅': 'eagle bird prey raptor sky aguila ave rapaz cielo vuelo garra pico rapaz cazador',
    '🦉': 'owl wisdom night bird hoot buho lechuza ave noche sabiduria ojos nocturno rapaces',
    '🦇': 'bat night vampire cave animal murcielago cueva noche vampiro alas bati volar radar',
    '🐺': 'wolf wild pack forest moon lobo aullido manada bosque salvaje luna aullar lupino',
    '🐗': 'boar wild pig tusks forest jabali cerdo salvaje colmillos bosque colmillo jabalina',
    '🐴': 'horse farm stallion animal caballo caballito corcel equino granja potro relinchar',
    '🦄': 'unicorn magical fantasy horse horn unicornio magico caballo fantasia cuerno arcoiris ensueño',
    '🐝': 'bee honeybee insect stinger miel abeja abejorro aguijon insecto miel polen colmena picadura',
    '🐛': 'bug caterpillar insect larva oruga bicho gusano insecto larva seda rastrero',
    '🦋': 'butterfly wings beauty insect flutter mariposa alas insecto bella capullo volar oruga',
    '🐌': 'snail slow shell garden garden caracol lento concha jardin babosa lentitud caparazon',
    '🐞': 'lady beetle ladybug insect spot mariquita vaquita de san antonio bicho mariquita roja puntos lunares',
    '🐜': 'ant insect work colony worker hormiga insecto trabajadora hormiguero hormiguitas obrera',
    '🦗': 'cricket grasshopper green insect grillo saltamontes insecto verde canto saltar chapulin',
    '🕷️': 'spider web eight arachnid araña tela telaraña aracnido patas ocho veneno arana',
    '🐢': 'turtle tortoise shell reptile slow tortuga caparazon reptil lenta verde agua marina galapago',
    '🐍': 'snake reptile hiss serpent viper serpiente reptil vivora culebra veneno escamas cobra cascabel',
    '🦎': 'lizard gecko reptile tail lagarto lagartija gecko reptil verde camaleon escamas',
    '🐙': 'octopus ocean sea tentacle cephalopod pulpo mar tentaculos oceano cefalopodo ventosas tinta',
    '🦑': 'squid ocean sea calamari squid calamar molusco oceano tentaculos calamar gigante',
    '🦐': 'shrimp prawn seafood shell camaron gamba marisco langostino mar concha cola de camaron',
    '🦞': 'lobster seafood ocean red claws langosta marisco pinzas rojas mar tenazas bogavante',
    '🦀': 'crab seafood ocean pinch crustacean cangrejo marisco pinzas crustaceo playa orilla caminar de lado',
    '🐡': 'blowfish pufferfish toxic sea pez globo inflado mar acuario espinas pez toxico veneno',
    '🐠': 'tropical fish aquarium color pez pez tropical pececito colores arrecife agua nemo marino',
    '🐟': 'fish sea aquatic swim food pez pescado nadar mar rio lago agua escamas acuatico',
    '🐬': 'dolphin sea ocean intelligent jump delfin oceano inteligente saltar acrobacia mar aleta salto',
    '🐳': 'spouting whale ocean giant mammal ballena gigante mar mamifero chorro de agua jorobada orca azul',
    '🦈': 'shark ocean predator jaws tooth tiburon aleta fauces depredador mar peligro dientes blanco',
    '🐊': 'crocodile alligator swamp reptile cocodrilo yacare reptil pantano dientes agua caiman verde',
    '🐅': 'tiger stripes wild animal stalking tigre cazador salvaje felino selva rayas bengala',
    '🐆': 'leopard panther spots spots animal leopardo pantera felino manchas veloz guepardo jaguar chita',
    '🦓': 'zebra stripes safari savanna animal cebra rayas blanco negro safari africa equino llanura',
    '🦍': 'gorilla ape silverback jungle gorila primate selva espalda plateada fuerza king kong mono',
    '🦧': 'orangutan ape monkey red jungle orangutan primate mono selva indonesia borneo peludo',
    '🦣': 'mammoth prehistoric extinct elephant mamut prehistorico extinto colmillos peludo era de hielo',
    '🐘': 'elephant tusks trunk safari giant elefante trompa colmillos mamifero orejas gigante sabana africa',
    '🦛': 'hippopotamus water safari river hipopotamo rio safari agua gigante pesado barro mandíbulas',
    '🦏': 'rhinoceros horn armor savanna safari rinoceronte cuerno salvaje blindado sabana cuerno marfil',
    '🐪': 'camel desert hump dry egypt camello una joroba dromedario desierto egipto arena caravana',
    '🐫': 'two-hump camel desert caravan bactrian camello dos jorobas desierto duna dos jorobas seda',
    '🦒': 'giraffe tall neck safari spots jirafa cuello largo alta manchas safari africa sabana hojas arbol',
    '🦘': 'kangaroo australia jump marsupial canguro salto australia marsupial bolsillo saltando cria',
    '🦬': 'bison buffalo prairie wild horned bisonte bufalo pradera cuernos manada campo indio americano',
    '🐃': 'water buffalo horn domestic cattle bufalo de agua toro astas cuernos fuerte lodazal',
    '🐂': 'ox bull cattle horns farm buey toro cuernos ganado fuerza arado bueyes castrado',
    '🐄': 'cow dairy farm cattle milk vaca lechera manchada leche granja campo ubre mu ternero',
    '🐎': 'horse race galloping stallion caballo al galope carrera equino veloz hipodromo jockey',
    '🐖': 'pig farm sow swine animal puerco cerdo chancho granja cuerpo entero marrano gordo lechon',
    '🐏': 'ram sheep horns fleece male carnero cuernos lana macho oveja rebaño chivo montaña',
    '🐑': 'sheep lamb wool fleece ewe oveja cordero lana ovejita balido campo rebaño pasto meee',
    '🦙': 'llama alpaca andes wool wool llama alpaca vicuña andes lana montaña altiplano escupir',
    '🐐': 'goat billy horn beard farm cabra chivo chivito cuernos barba granja monte queso cabrito',
    '🦌': 'deer buck fawn antlers forest ciervo venado bambi astas cuernos bosque bosque cazador reno',

    // Objects, Sports & Toys
    '🎁': 'wrapped gift present ribbon surprise box regalo obsequio paquete sorpresa caja moño lazo fiesta presente cumpleaños navidad',
    '⚡': 'high voltage lightning electricity shock bolt relampago rayo electricidad energia trueno chispa corriente voltaje tormenta',
    '⚽': 'soccer football ball sport goal futbol pelota balon gol deporte cancha patada messi pelota de futbol partido',
    '🏀': 'basketball ball sport court hoop basquet baloncesto pelota balon aro canasta deporte nba encestar canchita',
    '🏈': 'american football ball sport nfl futbol americano balon ovoide deporte super bowl yardas touchdown',
    '⚾': 'baseball ball sport strike bat beisbol pelota guante bate deporte lanzamiento home run base',
    '🥎': 'softball ball sport yellow softbol pelota amarilla guante juego lanzamiento',
    '🎾': 'tennis ball racket court match tenis pelota raqueta cancha saque deporte wimbledon tenis verde',
    '🏐': 'volleyball ball sport beach court voleibol voley pelota red playa deporte remate saque',
    '🥏': 'flying disc frisbee throw beach frisbee disco volador lanzar playa juego parque disco plastico',
    '🎱': 'pool 8 ball billiard game eight bola de billar ocho juego taco mesa billar bola negra juego de mesa',
    '🪀': 'yo-yo toy string spin trick yoyo yoyo juguete cuerda girar trucos juguete clasico retro',
    '🏓': 'ping pong table tennis paddle ball ping pong tenis de mesa paleta pelotita red tenis de mesa paletita',
    '🏸': 'badminton racket shuttlecock sport badminton raqueta pluma volante deporte gallito red',
    '🏒': 'ice hockey puck stick winter sport hockey sobre hielo palo disco patinaje deporte pista puck',
    '🥊': 'boxing glove fight sport punch guante de boxeo boxeo guantes pelea combate ring noqueo golpe pelea',
    '🥋': 'martial arts karate judo kimono judogi artes marciales karate judo taekwondo cinta negra combate lucha dojo',
    '🛹': 'skateboard skate board trick park patineta skate patinar tabla ruedas trucos rampa skater',
    '🛼': 'roller skate retro quad wheels patines sobre ruedas patinaje clasico cuatro ruedas patin patinar pista',
    '🚗': 'car automobile red sedan drive auto coche carro automovil vehiculo manejar rojo cuatro ruedas viaje transporte',
    '🚕': 'taxi cab yellow ride car taxi coche amarillo viaje transporte chofer pasajero tarifa libre',
    '🚙': 'suv recreational blue car suv auto camioneta 4x4 azul vehiculo todoterreno viaje familia',
    '🚌': 'bus school public transit coach autobus colectivo omnibus bondi micro transporte escolar parada pasaje',
    '🏎️': 'racing car formula speed race f1 auto de carreras carrera formula 1 pista velocidad piloto monoplaza gran premio',
    '🚓': 'police car emergency siren law patrullero auto de policia sirena justicia patrulla oficial policia alarma luces',
    '🚑': 'ambulance emergency hospital medical ambulancia emergencia hospital socorro medico sirena primeros auxilios paramedico',
    '🚒': 'fire engine truck extinguish firefighter camion de bomberos autobomba rescate fuego fuego manguera sirena bombero apagar',
    '🚐': 'minibus van camper transport furgoneta van combi furgon camioneta transporte camper combi viaje',
    '🛻': 'pickup truck bed payload cargo camioneta pickup chata carga camioneta flete caja de carga camionetita',
    '🚚': 'delivery truck lorry freight cargo camion reparto camion de carga entrega flete transporte envio paquetes',
    '🚛': 'articulated lorry semi truck freight camion con acoplado semirremolque trailer carga ruta remolque transporte pesado',
    '🚜': 'tractor farm field harvest agri tractor campo granja agricultura cosechar arar siembra rueda gigante motor',
    '🛵': 'motor scooter moped vespa bike scooter motoneta ciclomotor vespa moto moto dos ruedas paseo casco',
    '🏍️': 'motorcycle motor racer ride moto motocicleta pista dos ruedas velocidad ruta motoquera motero viajar',
    '🛺': 'auto rickshaw tuk tuk transport rickshaw mototaxi motocarro tuk tuk transporte tres ruedas asia',
    '🚲': 'bicycle bike ride cycle pedal bicicleta bici pedalear dos ruedas ciclista transporte paseo bmx casco ruedas',
    '🛴': 'kick scooter commute push monopatin scooter pata pata patineta manubrio ruedas patinete electrico',
    '🚀': 'rocket launch space ship fly cohete espacial despegue nave espacio cosmos nasa despegar luna marte volar',
    '🛸': 'flying saucer ufo alien extraterrestrial ovni platillo volador alien marciano nave espacio invasor platillo',
    '🚁': 'helicopter fly rotor blade copter helicoptero helice volar rescate nave transporte aire piloto aspas',
    '✈️': 'airplane aeroplane flight travel sky avion aeroplano volar viaje vuelo aeropuerto cielo alas pasaje turisteando',
    '⛵': 'sailboat boat sea yacht sail velero barco de vela mar navegar navegacion lago yate vela blanca brisa',
    '🚤': 'speedboat boat fast motor water lancha motora bote rapido agua rio motor velocidad paseo agua',
    '🚢': 'ship passenger cruise vessel boat barco buque crucero transatlantico navio navegar mar puerto travesia oceano',
    '🔔': 'bell ring alert notice alarm timbre campana alerta campanada notificacion sonar llamada campana de bronce aviso',
    '🔑': 'key lock password access secret llave dorada candado abrir clave cerrojo acceso contraseña puerta cerradura',
    '🎨': 'artist palette paint art brush color paleta de pintor arte pintura pintar pincel colores oleo acuarela artista cuadro',
    '🎲': 'game die dice roll chance casino dado dados juego de mesa tirar azar suerte ludo casino seis puntos tablero',
    '🎯': 'direct hit target bullseye bullseye tiro al blanco diana punteria flecha acierto centro acertar objetivo dardo diana',
    '🧸': 'teddy bear soft toy plush cuddly oso de peluche peluche tierno osito juguete muñeco peluchito abrazo abrazo',
    '💡': 'light bulb idea electricity bright bombilla foco lampara idea luz iluminacion bombillo ocurrencia pensar invento foco prendido',
    '📚': 'books library school study learn reading libros biblioteca estudiar escuela lectura leer tomos estudio cuaderno saber tomo',
    '✏️': 'pencil write school draw lead lapiz escribir dibujar escuela trazo mina goma borrador escribir dibujo nota',
    '🖍️': 'crayon draw color sketch wax crayola crayolita cera dibujar colorear niños pintar lapiz de cera colores',
    '🖌️': 'paintbrush art draw paint bristle pincel pintar brocha arte oleo acuarela cerdas pintar trazo cuadro lienzo',
    '📏': 'straight ruler measure length school regla regla recta medir centimetros longitud util escolar escala dibujo tecnico',
    '📐': 'triangular ruler measure math geometry escuadra cartabon regla triangulo geometria matematicas angulo grados dibujo',
    '✂️': 'scissors cut tool craft hair tijeras tijera cortar recorte papel manualidades peluqueria filo cortar papeles',
    '📌': 'pushpin pin map memo notice chincheta chinche pin mapa clavar anotacion corcho fijar nota alfiler',
    '📎': 'paperclip clip attach paper office clip sujetapapeles papel oficina juntar sujetador clip metalico notas',
    '🔒': 'locked closed padlock secure safe candado cerrado seguro privacidad clave proteccion cerrojo seguridad bajo llave',
    '🔓': 'unlocked open padlock unsecure free candado abierto disponible libre sin llave desbloqueado candado destrabado acceso',
    '🧲': 'magnet magnetic attraction pull imán iman atraccion magnetico magnetismo polaridad metal herradura polo norte sur',
    '🔭': 'telescope space stars astronomy sky telescopio astronomia estrellas cosmos planetas mirar cielo luna galaxia ocular',
    '🔬': 'microscope science lab research cell microscopio ciencia laboratorio investigar celula bacterias lentes aumento quimica',
    '🕹️': 'joystick game play arcade control palanca joystick videojuegos control fichas retro arcade palanca de juegos',
    '🎮': 'video game controller pad button play joystick mando consola control gamepad gamer jugar play playstation xbox switch',
    '🧩': 'puzzle piece jigsaw solve clue pieza de rompecabezas puzzle encastre acertijo juego logica pieza perdida armar',
    '🎸': 'guitar rock acoustic music instrument guitarra instrumento cuerdas musica recital tocar rock guitarra acustica electrica',
    '🎹': 'musical keyboard piano organ keys piano teclado instrumento notas musica acordes teclas sintetizador melodia clasica',
    '🎺': 'trumpet brass horn jazz music trompeta instrumento de viento metal jazz musica notas solo fanfarria bronce',
    '🎻': 'violin strings classical orchestra fiddle violin instrumento cuerdas orquesta clasica musica arco melodía violinista',
    '🥁': 'drum drumsticks rhythm beat band tambor bateria percusion ritmo redoblante baquetas musica golpear platillos redoble',

    // Nature, Plants & Weather
    '🌸': 'cherry blossom pink spring flower flor de cerezo flor rosada primavera flores sakura petalos jardin rosa',
    '🌺': 'hibiscus flower tropical hawaiian flor de hibisco flor roja tropical selva hawaii aloha petalos exotic',
    '🌻': 'sunflower yellow summer bright seed girasol flor amarilla sol semillas verano campo pipa girasoles soleado',
    '🌹': 'rose red love flower romantic valentine rosa roja amor flor romance san valentin petalos espinas rosal te amo',
    '🌷': 'tulip flower spring blossom holland tulipan flor tulipanes primavera holanda jardin bulbo tallo color',
    '🌼': 'blossom flower yellow daisy white flor margarita flor amarilla primavera petalos florecer manzanilla',
    '💐': 'bouquet flowers gift romance celebration ramo de flores arreglo flores regalo bouquet rosas flores varias festejo felicitacion',
    '🌾': 'sheaf of rice crop grain harvest espiga arroz trigo cereal cosecha campo granos avena siembra campo',
    '🌿': 'herb green leaf plant sprig hierba hoja verde planta brote medicina aroma ramita culantro perejil menta',
    '🍀': 'four leaf clover luck fortune irish trebol de cuatro hojas suerte trebol verde fortuna san patricio trébol irlandes buena suerte',
    '🍁': 'maple leaf autumn fall orange canada hoja de arce arce otoño hoja roja seca canada arbol otoñal caduca',
    '🍂': 'fallen leaf dry autumn leaves wind hojas caidas otoño hojas secas viento marron suelo doradas hojarasca',
    '🍃': 'leaf fluttering in wind breeze green hojas al viento brisa verde follaje naturaleza aire hoja verde arbol',
    '🌲': 'evergreen tree pine forest nature pino arbol abeto bosque naturaleza montaña conifera pinar navidad madera',
    '🌳': 'deciduous tree green tree park shade arbol arbol frondoso parque verde bosque sombra copa roble follaje vida',
    '🌴': 'palm tree tropical beach vacation island palmera playa tropical isla vacaciones coco arena sol caribe calor verano',
    '🌵': 'cactus desert dry thorny spike cactus cacto desierto espinas sequia planta arido suculenta clima calido',
    '🌱': 'seedling plant sprout growth green brote plantita germinado semilla crecimiento verde planta maceta huerta cultivar vida',
    '🪴': 'potted plant houseplant indoor decor planta en maceta maceta interior verde hojas decoracion macetita cuidar regar',
    '🌍': 'globe earth europe africa world planet globo terraqueo planeta tierra europa africa mundo continente mapa esfera mapa mundo',
    '🌎': 'globe earth americas world planet globo terraqueo planeta tierra america nuevo mundo continente globo mapa sudamerica norteamerica',
    '🌏': 'globe earth asia australia world planet globo terraqueo planeta tierra asia oceania australia mundo oriente globo mapa',
    '🌕': 'full moon bright lunar night sky luna llena brillante noche cielo crateres redonda satelite noche estrellada',
    '🌙': 'crescent moon night dream sleep bedtime luna creciente luna cuarto menguante noche dormir sueño buenas noches dormirse',
    '💫': 'dizzy star spark swirl shine destello chispas estrellas giratorias mareo brillo magia polvo de estrellas marearse',
    '🪐': 'ringed planet saturn orbit cosmos espacio planeta con anillos saturno cosmos orbita galaxia universo astronomia',
    '☀️': 'sun sunny sunshine bright warm hot sol soleado dia brillante luz calor rayos radiante buen tiempo verano astro rey',
    '🌤️': 'sun behind small cloud day warm sol tras pequeña nube dia claro templado parcialmente soleado buen clima templado',
    '⛅': 'sun behind cloud cloudy partial sol detras de una nube nublado parcial templado sombra clima suave',
    '🌥️': 'sun behind large cloud overcast sol oculto gran nube nuboso gris dia fresco tapado nubarrón',
    '☁️': 'cloud overcast weather sky white nube cielo nublado tiempo clima blanco algodon nubecita cumulo tapado',
    '🌦️': 'sun behind rain cloud shower arcoiris sol con lluvia chubasco chaparrón arco iris llovizna agua sol y lluvia',
    '🌧️': 'cloud with rain storm wet weather nube con lluvia lloviendo lluvia gotas tormenta agua mojado paraguas precipitaciones',
    '⛈️': 'cloud lightning rain thunder storm tormenta electrica rayos truenos relampagos chubasco lluvia fuerte tempestad trueno truena',
    '🌩️': 'cloud with lightning flash thunder nube con rayo relampago trueno tormenta tempestad descarga trueno trueno',
    '🌨️': 'cloud with snow blizzard cold winter nube con nieve nevando nevada copos frio helado invierno nevisca esquiar',
    '❄️': 'snowflake snow cold ice crystal winter copo de nieve nieve copito hielo cristal frio invierno helado copo helada congelado',
    '☃️': 'snowman with snow cold winter frozen muñeco de nieve muñeco de nieve nieve invierno frio bufanda helado congelado navidad',
    '⛄': 'snowman winter holiday cute frost muñeco de nieve sin nieve frio helado alegre blanco navidad muñequito',
    '🌬️': 'wind face blowing breeze air cold viento soplando cara de viento brisa rafaga aire soplar eolo temporal ventarron',
    '💨': 'dashing away fast speed smoke puff saliendo disparado humo viento rapido corriendo escape velocidad polvo veloz huir gas',
    '🌪️': 'tornado twister cyclone vortex storm tornado remolino ciclon torbellino tormenta desastre viento destruccion tromba',
    '🌈': 'rainbow colors pride sky weather arcoiris arco iris colores cielo lluvia sol magia alegria diversidad cielo hermoso',
    '🌊': 'water wave ocean tsunami sea surf ola de agua ola gigante tsunami mar oceano surf oleaje resaca marea chapuzon',
    '💧': 'droplet water sweat tear liquid raindrop gota de agua agua gota liquido rocio sudor lagrima hidro rociar',

    // Math, Numbers & Shapes
    '➕': 'plus sign addition sum math cross signo mas suma adiccion positivo agregar matematicas mas contar suma',
    '➖': 'minus sign subtraction difference math line signo menos resta sustraccion negativo restar linea menos restar guion',
    '✖️': 'multiplication sign multiply times x cross signo de multiplicacion por multiplicar producto equis producto tablas multiplicar cuenta',
    '➗': 'division sign divide by over math obelus signo de division dividido dividir cociente reparto matematicas fraccion dividir calcular',
    '🟰': 'heavy equals sign equal result is identical signo igual es igual igualdad resultado idéntico equivalente cuenta matematicas igual a',
    '🔴': 'red circle shape round dot rojo circulo punto redondo figura bola pelota boton ficha color rojo circulo rojo',
    '🔵': 'blue circle shape round dot azul circulo punto redondo figura bola boton ficha color azul circulo azul',
    '🟡': 'yellow circle shape round dot amarillo circulo punto redondo figura bola boton ficha color amarillo circulo amarillo',
    '🟢': 'green circle shape round dot verde circulo punto redondo figura bola boton ficha color verde circulo verde',
    '🟣': 'purple circle shape round dot violeta morado circulo punto redondo figura bola boton ficha color purpura circulo violeta',
    '🟠': 'orange circle shape round dot naranja circulo punto redondo figura bola boton ficha color naranja circulo naranja',
    '🟤': 'brown circle shape round dot marron café circulo punto redondo figura bola boton ficha color marron circulo cafe',
    '⬛': 'black square shape quad box negro cuadrado figura caja boton bloque ficha color negro cuadrado negro',
    '⬜': 'white square shape quad box blanco cuadrado figura caja boton bloque ficha color blanco cuadrado blanco',
    '🔺': 'red triangle pointed up arrow rojo triangulo hacia arriba flecha triangulito delta figura geometrica subida punta',
    '🔻': 'red triangle pointed down arrow rojo triangulo hacia abajo flecha descendente triangulito bajada punta abajo',
    '🔹': 'small blue diamond gem shape azul rombo pequeño diamante gema figura rombo azul figura geometrica',
    '🔶': 'large orange diamond shape gem naranja rombo grande romboide gema figura rombo naranja figura geometrica',
    '🔷': 'large blue diamond shape gem azul rombo grande romboide gema figura rombo azul grande figura geometrica',
    '🔸': 'small orange diamond shape gem naranja rombo pequeño gema figura rombo naranja chico figura geometrica',
    '💠': 'diamond with dot cute flower pattern rombo con punto flor geometrica figura mandala simbolo diamante',
    '🔘': 'radio button select circle target boton de opcion seleccionar radiobutton circulo marcado opcion seleccion casilla',
    '⚪': 'white circle round dot shape blanco circulo redondo punto esfera pelota ficha blanca circulo blanco',
    '⚫': 'black circle round dot shape negro circulo redondo punto esfera boton ficha negra circulo negro',
    '🟥': 'red square shape block box rojo cuadrado bloque figura rojo cuadro color rojo cuadrado rojo',
    '🟧': 'orange square shape block box naranja cuadrado bloque figura naranja cuadro color naranja cuadrado naranja',
    '🟨': 'yellow square shape block box amarillo cuadrado bloque figura amarillo cuadro color amarillo cuadrado amarillo',
    '🟩': 'green square shape block box verde cuadrado bloque figura verde cuadro color verde cuadrado verde',
    '🟦': 'blue square shape block box azul cuadrado bloque figura azul cuadro color azul cuadrado azul',
    '🟪': 'purple square shape block box morado violeta cuadrado bloque figura cuadro color morado violeta cuadrado purpura',
    '🟫': 'brown square shape block box marron café cuadrado bloque figura cuadro color marron cuadrado cafe',
    '💯': 'hundred points score perfect 100 test cien puntos nota cien perfecto examen excelente 100% aprobado felicitaciones diez',
    '❓': 'question mark interrogation what why signo de interrogacion pregunta duda que por que que paso interrogante que interrogacion',
    '❗': 'exclamation mark alert danger surprise signo de exclamacion alerta atencion advertencia sorpresa peligro exclamacion admiracion aviso',
    '1️⃣': 'one keycap number 1 digit primer primero uno tecla numero 1 cifra digito valor uno numero uno',
    '2️⃣': 'two keycap number 2 digit segundo dos tecla numero 2 cifra digito valor dos numero dos',
    '3️⃣': 'three keycap number 3 digit tercero tres tecla numero 3 cifra digito valor tres numero tres',
    '4️⃣': 'four keycap number 4 digit cuarto cuatro tecla numero 4 cifra digito valor cuatro numero cuatro',
    '5️⃣': 'five keycap number 5 digit quinto cinco tecla numero 5 cifra digito valor cinco numero cinco',
    '6️⃣': 'six keycap number 6 digit sexto seis tecla numero 6 cifra digito valor seis numero seis',
    '7️⃣': 'seven keycap number 7 digit septimo siete tecla numero 7 cifra digito valor siete numero siete',
    '8️⃣': 'eight keycap number 8 digit octavo ocho tecla numero 8 cifra digito valor ocho numero ocho',
    '9️⃣': 'nine keycap number 9 digit noveno nueve tecla numero 9 cifra digito valor nueve numero nueve',
    '🔟': 'ten keycap number 10 digit decimo diez tecla numero 10 cifra digito valor diez numero diez',
    '🔢': 'input numbers 1234 math count keyboard teclado de numeros numeros digitos cifras contar matematicas teclado numerico 1234',
    '🔣': 'input symbols math symbols glyphs simbolos matematicas signos caracteres teclas simbolo caracteres especiales',
    '🚫': 'prohibited forbidden no entry stop banned cancel no prohibido prohibicion no pasar cancelado bloqueado denegado',
    '⛔': 'no entry stop sign road barrier prohibited prohibido el paso no entrar sentido contrario stop alto',
    '❌': 'cross mark x cancel wrong bad error incorrect cruz roja marca equis incorrecto mal error cancelar tachado',
    '⭕': 'heavy large circle red o correct ring circulo rojo correcto bien marca aro',
    '🛑': 'stop sign octagon red signal road alto parada detenerse cartel de stop señal roja trafico',
    '⚠️': 'warning caution alert danger hazard triangle advertencia peligro cuidado precaucion triangulo amarillo atencion',
    '🚷': 'no pedestrians prohibited walking prohibido peatones no caminar prohibido pasar caminando',
    '🚭': 'no smoking cigarettes prohibited no fumar prohibido fumar tabaco cigarro',
    '🚯': 'no littering prohibited trash no arrojar basura prohibido tirar basura limpio',
    '🔇': 'muted speaker silent sound off no audio mudo silencio silenciado sin volumen sin sonido altavoz tachado',
    '🔕': 'bell with slash muted notification off sin campana silenciado no molestar aviso apagado',
    '🔞': 'no one under eighteen 18 adult mature prohibido menores 18 años adultos edad prohibido chicos',
    '☢️': 'radioactive radiation nuclear danger hazard radiactivo peligro nuclear residuo atomico advertencia',
    '☣️': 'biohazard biological danger virus hazard peligro biologico virus infeccioso riesgo toxico',
    '✅': 'check mark button green white checkmark tick ok correcto verificado tilde palomita aprobado listo bien',
    '✔️': 'check mark tick ok correct done tilde marca verificado aprobado bien si correcto',
    '☑️': 'ballot box with check checkbox voted square casilla marcada voto seleccionado tilde tildado',
    '➡️': 'right arrow forward direction next flecha derecha adelante siguiente continuar',
    '⬅️': 'left arrow back direction previous flecha izquierda atras anterior volver retroceder',
    '⬆️': 'up arrow north top increase flecha arriba subir norte elevar',
    '⬇️': 'down arrow south bottom decrease flecha abajo bajar sur descender',
    '↗️': 'up-right arrow diagonal flecha arriba derecha diagonal norte este',
    '↘️': 'down-right arrow diagonal flecha abajo derecha diagonal sur este',
    '↙️': 'down-left arrow diagonal flecha abajo izquierda diagonal sur oeste',
    '↖️': 'up-left arrow diagonal flecha arriba izquierda diagonal norte oeste',
    '↕️': 'up-down arrow vertical bidirectional flecha arriba abajo vertical doble sentido',
    '↔️': 'left-right arrow horizontal bidirectional flecha izquierda derecha horizontal doble sentido',
    '🔄': 'counterclockwise arrows button refresh reload loop update flecha circular recargar actualizar reiniciar repetir bucle',
    '🔃': 'clockwise vertical arrows reload repeat sync flechas circulares sincronizar girar rotar refrescar',
    '🔀': 'shuffle tracks button random mix aleatorio mezclar canciones shuffle orden al azar',
    '🔁': 'repeat button loop replay track repetir bucle volver a reproducir ciclo bucle',
    '🔂': 'repeat single track once button repetir una cancion pista bucle unico',
    '▶️': 'play button run start audio video reproducir play iniciar comienzo arrancar',
    '⏸️': 'pause button wait hold audio pausa pausar detener momento esperar',
    '⏹️': 'stop button end audio video detener parar finalizar stop',
    '⏺️': 'record button audio video grabar grabacion registro punto rojo',
    '⏭️': 'next track button forward saltar siguiente avanzar pista siguiente',
    '⏮️': 'previous track button rewind volver anterior pista previa retroceder',
    '⏩': 'fast forward button speed avanzar rapido velocidad adelante',
    '⏪': 'fast reverse button rewind rebobinar atras rapido retroceder',
    '🔍': 'magnifying glass search find inspect lupa buscar encontrar busqueda investigar ver',
    '🔎': 'magnifying glass right search inspect lupa a la derecha buscar inspeccionar examen',
    '📢': 'loudspeaker announcement broadcast megáfono altavoz aviso anuncio grito difusion publicidad',
    '📣': 'megaphone cheering announcement corneta megáfono aliento arenga grito aviso',
    '💬': 'speech balloon text comment message chat burbuja de dialogo mensaje texto conversacion chat comentario',
    '💭': 'thought balloon think dream cloud nube de pensamiento pensar sueño idea mente',
    '🗯️': 'anger bubble angry shout explode globo de ira grito furia enojo explosion',
    '✉️': 'envelope letter mail email postal sobre carta correo mensaje correspondencia email',
    '📧': 'email e-mail mail electronic message correo electronico mensaje email arroba',
    '📝': 'memo pencil paper write note memo nota escribir lapiz borrador apunte redactar texto',
    '🖊️': 'pen write ink ballpoint birome boligrafo lapicera pluma tinta firmar',
    '🖋️': 'fountain pen elegant signature write pluma estilografica tinta pluma firma caligrafia',
    '📍': 'round pushpin location pin map mark chincheta redonda ubicacion mapa lugar destino gps',
    '🗑️': 'wastebasket trash can bin delete delete cesto de basura papelera tacho eliminar borrar descarte',
    '📱': 'mobile phone smartphone screen call celular telefono movil pantalla llamada smartphone iphone',
    '💻': 'laptop computer pc tech screen notebook computadora portatil notebook ordenador pantalla trabajar',
    '🖥️': 'desktop computer pc monitor screen computadora de escritorio pc monitor pantalla gabinete',
    '🖨️': 'printer print paper document office impresora imprimir papel documento copia tinta',
    '⌨️': 'keyboard type typing keys button teclado teclas escribir tipear computacion periférico',
    '⏱️': 'stopwatch timer measure time speed cronometro tiempo medir segundos velocidad carrera',
    '⏲️': 'timer clock countdown alarm temporizador reloj cuenta regresiva alarma cocina tiempo',
    '⏰': 'alarm clock morning wake up ring despertador reloj despertador alarma campana mañana sonar',
    '⌛': 'hourglass time sand passing waiting reloj de arena tiempo arena pasando espera paciencia reloj',
    '⏳': 'hourglass flowing sand waiting timer reloj de arena fluyendo cuenta espera paciencia',
    '🏁': 'chequered flag race finish winner bandera a cuadros meta carrera final ganador automovilismo llegada',
    '🚩': 'triangular flag post red signal red flag bandera roja señal aviso alerta marca banderin',
    '🎌': 'crossed flags celebration japan festival banderas cruzadas celebracion festejo fiesta',
    '🥇': '1st place medal gold first winner medalla de oro primer lugar campeon primero ganador triunfo',
    '🥈': '2nd place medal silver second medalla de plata segundo lugar medalla subcampeon',
    '🥉': '3rd place medal bronze third medalla de bronce tercer lugar medalla tercero puesto',
};
