/**
 * Auto-generated asset metadata from Original Game CSVs
 * Generated by scripts/generateAssetData.js
 */
export const ASSETS = {
  "titlecard": {
    "id": "titlecard",
    "name": "TitleCard",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/titlecard.png",
    "regX": 0,
    "regY": 0
  },
  "titlecard2": {
    "id": "titlecard2",
    "name": "TitleCard2",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/titlecard2.png",
    "regX": 0,
    "regY": 0
  },
  "newsgaming_logo": {
    "id": "newsgaming_logo",
    "name": "NewsgamingLogo",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/newsgaming-logo.png",
    "regX": 0,
    "regY": 0
  },
  "3_2": {
    "id": "3_2",
    "name": "Map",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_2.png",
    "regX": 640,
    "regY": 240
  },
  "3_206": {
    "id": "3_206",
    "name": "casa011",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_206.png",
    "regX": 77,
    "regY": 85
  },
  "3_207": {
    "id": "3_207",
    "name": "casa021",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_207.png",
    "regX": 55,
    "regY": 78
  },
  "3_208": {
    "id": "3_208",
    "name": "casa031",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_208.png",
    "regX": 33,
    "regY": 62
  },
  "3_209": {
    "id": "3_209",
    "name": "casa041",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_209.png",
    "regX": 43,
    "regY": 102
  },
  "3_210": {
    "id": "3_210",
    "name": "casa051",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_210.png",
    "regX": 43,
    "regY": 81
  },
  "3_211": {
    "id": "3_211",
    "name": "casa061",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_211.png",
    "regX": 52,
    "regY": 80
  },
  "3_212": {
    "id": "3_212",
    "name": "edificio011",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_212.png",
    "regX": 36,
    "regY": 128
  },
  "3_213": {
    "id": "3_213",
    "name": "edificio021",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_213.png",
    "regX": 42,
    "regY": 119
  },
  "3_214": {
    "id": "3_214",
    "name": "edificio031",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_214.png",
    "regX": 56,
    "regY": 127
  },
  "3_215": {
    "id": "3_215",
    "name": "edificio041",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_215.png",
    "regX": 51,
    "regY": 138
  },
  "3_216": {
    "id": "3_216",
    "name": "edificio051",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_216.png",
    "regX": 68,
    "regY": 117
  },
  "3_217": {
    "id": "3_217",
    "name": "edificio061",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_217.png",
    "regX": 63,
    "regY": 100
  },
  "3_218": {
    "id": "3_218",
    "name": "fuente011",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_218.png",
    "regX": 24,
    "regY": 35
  },
  "3_219": {
    "id": "3_219",
    "name": "fuente021",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_219.png",
    "regX": 32,
    "regY": 40
  },
  "3_220": {
    "id": "3_220",
    "name": "palmera011",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_220.png",
    "regX": 20,
    "regY": 81
  },
  "3_221": {
    "id": "3_221",
    "name": "palmera021",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_221.png",
    "regX": 11,
    "regY": 68
  },
  "3_222": {
    "id": "3_222",
    "name": "palmera031",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_222.png",
    "regX": 31,
    "regY": 69
  },
  "3_223": {
    "id": "3_223",
    "name": "palmera041",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_223.png",
    "regX": 18,
    "regY": 71
  },
  "3_224": {
    "id": "3_224",
    "name": "palmera051",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_224.png",
    "regX": 17,
    "regY": 64
  },
  "3_225": {
    "id": "3_225",
    "name": "palmera061",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_225.png",
    "regX": 10,
    "regY": 70
  },
  "3_226": {
    "id": "3_226",
    "name": "palmera071",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_226.png",
    "regX": 30,
    "regY": 72
  },
  "3_227": {
    "id": "3_227",
    "name": "palmera081",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_227.png",
    "regX": 9,
    "regY": 78
  },
  "3_228": {
    "id": "3_228",
    "name": "palmera091",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_228.png",
    "regX": 29,
    "regY": 77
  },
  "3_229": {
    "id": "3_229",
    "name": "palmera101",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_229.png",
    "regX": 9,
    "regY": 67
  },
  "3_230": {
    "id": "3_230",
    "name": "palmera111",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_230.png",
    "regX": 19,
    "regY": 74
  },
  "3_231": {
    "id": "3_231",
    "name": "palmera121",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_231.png",
    "regX": 7,
    "regY": 63
  },
  "3_232": {
    "id": "3_232",
    "name": "puesto011",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_232.png",
    "regX": 24,
    "regY": 28
  },
  "3_233": {
    "id": "3_233",
    "name": "puesto021",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_233.png",
    "regX": 18,
    "regY": 54
  },
  "3_234": {
    "id": "3_234",
    "name": "puesto031",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_234.png",
    "regX": 28,
    "regY": 61
  },
  "3_235": {
    "id": "3_235",
    "name": "puesto041",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_235.png",
    "regX": 23,
    "regY": 53
  },
  "3_236": {
    "id": "3_236",
    "name": "puesto051",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_236.png",
    "regX": 34,
    "regY": 44
  },
  "3_237": {
    "id": "3_237",
    "name": "puesto061",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_237.png",
    "regX": 35,
    "regY": 50
  },
  "3_238": {
    "id": "3_238",
    "name": "puesto071",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_238.png",
    "regX": 31,
    "regY": 57
  },
  "3_239": {
    "id": "3_239",
    "name": "puesto081",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_239.png",
    "regX": 47,
    "regY": 64
  },
  "3_240": {
    "id": "3_240",
    "name": "casa012",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_240.png",
    "regX": 77,
    "regY": 81
  },
  "3_241": {
    "id": "3_241",
    "name": "casa013",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_241.png",
    "regX": 71,
    "regY": 68
  },
  "3_242": {
    "id": "3_242",
    "name": "casa022",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_242.png",
    "regX": 61,
    "regY": 77
  },
  "3_243": {
    "id": "3_243",
    "name": "casa023",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_243.png",
    "regX": 63,
    "regY": 80
  },
  "3_244": {
    "id": "3_244",
    "name": "casa032",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_244.png",
    "regX": 30,
    "regY": 52
  },
  "3_245": {
    "id": "3_245",
    "name": "casa033",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_245.png",
    "regX": 43,
    "regY": 39
  },
  "3_246": {
    "id": "3_246",
    "name": "casa042",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_246.png",
    "regX": 45,
    "regY": 103
  },
  "3_247": {
    "id": "3_247",
    "name": "casa043",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_247.png",
    "regX": 51,
    "regY": 88
  },
  "3_248": {
    "id": "3_248",
    "name": "casa052",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_248.png",
    "regX": 43,
    "regY": 81
  },
  "3_249": {
    "id": "3_249",
    "name": "casa053",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_249.png",
    "regX": 46,
    "regY": 65
  },
  "3_250": {
    "id": "3_250",
    "name": "casa062",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_250.png",
    "regX": 55,
    "regY": 77
  },
  "3_251": {
    "id": "3_251",
    "name": "casa063",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_251.png",
    "regX": 54,
    "regY": 59
  },
  "3_252": {
    "id": "3_252",
    "name": "edificio012",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_252.png",
    "regX": 41,
    "regY": 129
  },
  "3_253": {
    "id": "3_253",
    "name": "edificio013",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_253.png",
    "regX": 42,
    "regY": 87
  },
  "3_254": {
    "id": "3_254",
    "name": "edificio014",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_254.png",
    "regX": 45,
    "regY": 71
  },
  "3_255": {
    "id": "3_255",
    "name": "edificio022",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_255.png",
    "regX": 41,
    "regY": 118
  },
  "3_256": {
    "id": "3_256",
    "name": "edificio023",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_256.png",
    "regX": 42,
    "regY": 92
  },
  "3_257": {
    "id": "3_257",
    "name": "edificio024",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_257.png",
    "regX": 42,
    "regY": 76
  },
  "3_258": {
    "id": "3_258",
    "name": "edificio032",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_258.png",
    "regX": 56,
    "regY": 126
  },
  "3_259": {
    "id": "3_259",
    "name": "edificio033",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_259.png",
    "regX": 65,
    "regY": 110
  },
  "3_260": {
    "id": "3_260",
    "name": "edificio034",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_260.png",
    "regX": 74,
    "regY": 75
  },
  "3_261": {
    "id": "3_261",
    "name": "edificio042",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_261.png",
    "regX": 66,
    "regY": 119
  },
  "3_262": {
    "id": "3_262",
    "name": "edificio043",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_262.png",
    "regX": 65,
    "regY": 90
  },
  "3_263": {
    "id": "3_263",
    "name": "edificio044",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_263.png",
    "regX": 73,
    "regY": 68
  },
  "3_264": {
    "id": "3_264",
    "name": "edificio052",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_264.png",
    "regX": 71,
    "regY": 119
  },
  "3_265": {
    "id": "3_265",
    "name": "edificio053",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_265.png",
    "regX": 75,
    "regY": 101
  },
  "3_266": {
    "id": "3_266",
    "name": "edificio054",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_266.png",
    "regX": 75,
    "regY": 67
  },
  "3_267": {
    "id": "3_267",
    "name": "edificio062",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_267.png",
    "regX": 63,
    "regY": 100
  },
  "3_268": {
    "id": "3_268",
    "name": "edificio063",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_268.png",
    "regX": 62,
    "regY": 89
  },
  "3_269": {
    "id": "3_269",
    "name": "edificio064",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_269.png",
    "regX": 68,
    "regY": 82
  },
  "3_270": {
    "id": "3_270",
    "name": "palmera012",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_270.png",
    "regX": 32,
    "regY": 71
  },
  "3_271": {
    "id": "3_271",
    "name": "palmera013",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_271.png",
    "regX": 7,
    "regY": 22
  },
  "3_272": {
    "id": "3_272",
    "name": "palmera022",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_272.png",
    "regX": 11,
    "regY": 46
  },
  "3_273": {
    "id": "3_273",
    "name": "palmera023",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_273.png",
    "regX": 16,
    "regY": 16
  },
  "3_274": {
    "id": "3_274",
    "name": "palmera032",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_274.png",
    "regX": 57,
    "regY": 13
  },
  "3_275": {
    "id": "3_275",
    "name": "palmera033",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_275.png",
    "regX": 52,
    "regY": 12
  },
  "3_276": {
    "id": "3_276",
    "name": "palmera042",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_276.png",
    "regX": 29,
    "regY": 59
  },
  "3_277": {
    "id": "3_277",
    "name": "palmera043",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_277.png",
    "regX": 10,
    "regY": 14
  },
  "3_278": {
    "id": "3_278",
    "name": "palmera052",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_278.png",
    "regX": 22,
    "regY": 46
  },
  "3_279": {
    "id": "3_279",
    "name": "palmera053",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_279.png",
    "regX": 26,
    "regY": 13
  },
  "3_280": {
    "id": "3_280",
    "name": "palmera062",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_280.png",
    "regX": 7,
    "regY": 44
  },
  "3_281": {
    "id": "3_281",
    "name": "palmera063",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_281.png",
    "regX": 10,
    "regY": 13
  },
  "3_282": {
    "id": "3_282",
    "name": "palmera072",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_282.png",
    "regX": 68,
    "regY": 23
  },
  "3_283": {
    "id": "3_283",
    "name": "palmera073",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_283.png",
    "regX": 10,
    "regY": 13
  },
  "3_284": {
    "id": "3_284",
    "name": "palmera082",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_284.png",
    "regX": 5,
    "regY": 65
  },
  "3_285": {
    "id": "3_285",
    "name": "palmera083",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_285.png",
    "regX": 13,
    "regY": 14
  },
  "3_286": {
    "id": "3_286",
    "name": "palmera092",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_286.png",
    "regX": 7,
    "regY": 44
  },
  "3_287": {
    "id": "3_287",
    "name": "palmera093",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_287.png",
    "regX": 10,
    "regY": 13
  },
  "3_288": {
    "id": "3_288",
    "name": "palmera102",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_288.png",
    "regX": 22,
    "regY": 17
  },
  "3_289": {
    "id": "3_289",
    "name": "palmera103",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_289.png",
    "regX": 10,
    "regY": 13
  },
  "3_290": {
    "id": "3_290",
    "name": "palmera112",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_290.png",
    "regX": 12,
    "regY": 57
  },
  "3_291": {
    "id": "3_291",
    "name": "palmera113",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_291.png",
    "regX": 14,
    "regY": 17
  },
  "3_292": {
    "id": "3_292",
    "name": "palmera122",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_292.png",
    "regX": 18,
    "regY": 40
  },
  "3_293": {
    "id": "3_293",
    "name": "palmera123",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_293.png",
    "regX": 14,
    "regY": 17
  },
  "3_294": {
    "id": "3_294",
    "name": "puesto012",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_294.png",
    "regX": 22,
    "regY": 27
  },
  "3_295": {
    "id": "3_295",
    "name": "puesto013",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_295.png",
    "regX": 23,
    "regY": 21
  },
  "3_296": {
    "id": "3_296",
    "name": "puesto022",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_296.png",
    "regX": 24,
    "regY": 51
  },
  "3_297": {
    "id": "3_297",
    "name": "puesto023",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_297.png",
    "regX": 23,
    "regY": 22
  },
  "3_298": {
    "id": "3_298",
    "name": "puesto032",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_298.png",
    "regX": 34,
    "regY": 60
  },
  "3_299": {
    "id": "3_299",
    "name": "puesto033",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_299.png",
    "regX": 31,
    "regY": 44
  },
  "3_300": {
    "id": "3_300",
    "name": "puesto042",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_300.png",
    "regX": 27,
    "regY": 62
  },
  "3_301": {
    "id": "3_301",
    "name": "puesto043",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_301.png",
    "regX": 25,
    "regY": 46
  },
  "3_302": {
    "id": "3_302",
    "name": "puesto052",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_302.png",
    "regX": 27,
    "regY": 33
  },
  "3_303": {
    "id": "3_303",
    "name": "puesto053",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_303.png",
    "regX": 28,
    "regY": 29
  },
  "3_304": {
    "id": "3_304",
    "name": "puesto062",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_304.png",
    "regX": 36,
    "regY": 49
  },
  "3_305": {
    "id": "3_305",
    "name": "puesto063",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_305.png",
    "regX": 35,
    "regY": 42
  },
  "3_306": {
    "id": "3_306",
    "name": "puesto072",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_306.png",
    "regX": 41,
    "regY": 53
  },
  "3_307": {
    "id": "3_307",
    "name": "puesto073",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_307.png",
    "regX": 32,
    "regY": 40
  },
  "3_308": {
    "id": "3_308",
    "name": "puesto082",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_308.png",
    "regX": 48,
    "regY": 63
  },
  "3_309": {
    "id": "3_309",
    "name": "puesto083",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_309.png",
    "regX": 48,
    "regY": 36
  },
  "3_310": {
    "id": "3_310",
    "name": "fuente012",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_310.png",
    "regX": 31,
    "regY": 40
  },
  "3_311": {
    "id": "3_311",
    "name": "fuente013",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_311.png",
    "regX": 27,
    "regY": 32
  },
  "3_312": {
    "id": "3_312",
    "name": "fuente022",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_312.png",
    "regX": 31,
    "regY": 38
  },
  "3_313": {
    "id": "3_313",
    "name": "fuente023",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_313.png",
    "regX": 37,
    "regY": 37
  },
  "3_314": {
    "id": "3_314",
    "name": "edificio015",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_314.png",
    "regX": 50,
    "regY": 88
  },
  "3_315": {
    "id": "3_315",
    "name": "edificio016",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_315.png",
    "regX": 49,
    "regY": 92
  },
  "3_316": {
    "id": "3_316",
    "name": "edificio017",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_316.png",
    "regX": 52,
    "regY": 120
  },
  "3_317": {
    "id": "3_317",
    "name": "edificio018",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_317.png",
    "regX": 52,
    "regY": 133
  },
  "3_318": {
    "id": "3_318",
    "name": "edificio019",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_318.png",
    "regX": 51,
    "regY": 137
  },
  "3_319": {
    "id": "3_319",
    "name": "edificio025",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_319.png",
    "regX": 52,
    "regY": 79
  },
  "3_320": {
    "id": "3_320",
    "name": "edificio026",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_320.png",
    "regX": 51,
    "regY": 94
  },
  "3_321": {
    "id": "3_321",
    "name": "edificio027",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_321.png",
    "regX": 54,
    "regY": 110
  },
  "3_322": {
    "id": "3_322",
    "name": "edificio028",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_322.png",
    "regX": 54,
    "regY": 117
  },
  "3_323": {
    "id": "3_323",
    "name": "edificio029",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_323.png",
    "regX": 58,
    "regY": 123
  },
  "3_324": {
    "id": "3_324",
    "name": "edificio035",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_324.png",
    "regX": 61,
    "regY": 92
  },
  "3_325": {
    "id": "3_325",
    "name": "edificio036",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_325.png",
    "regX": 73,
    "regY": 95
  },
  "3_326": {
    "id": "3_326",
    "name": "edificio037",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_326.png",
    "regX": 63,
    "regY": 102
  },
  "3_327": {
    "id": "3_327",
    "name": "edificio038",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_327.png",
    "regX": 65,
    "regY": 122
  },
  "3_328": {
    "id": "3_328",
    "name": "edificio039",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_328.png",
    "regX": 63,
    "regY": 128
  },
  "3_329": {
    "id": "3_329",
    "name": "edificio045",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_329.png",
    "regX": 51,
    "regY": 74
  },
  "3_330": {
    "id": "3_330",
    "name": "edificio046",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_330.png",
    "regX": 51,
    "regY": 89
  },
  "3_331": {
    "id": "3_331",
    "name": "edificio047",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_331.png",
    "regX": 67,
    "regY": 118
  },
  "3_332": {
    "id": "3_332",
    "name": "edificio048",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_332.png",
    "regX": 66,
    "regY": 138
  },
  "3_333": {
    "id": "3_333",
    "name": "edificio049",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_333.png",
    "regX": 65,
    "regY": 137
  },
  "3_334": {
    "id": "3_334",
    "name": "edificio055",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_334.png",
    "regX": 81,
    "regY": 86
  },
  "3_335": {
    "id": "3_335",
    "name": "edificio056",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_335.png",
    "regX": 81,
    "regY": 106
  },
  "3_336": {
    "id": "3_336",
    "name": "edificio057",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_336.png",
    "regX": 87,
    "regY": 114
  },
  "3_337": {
    "id": "3_337",
    "name": "edificio058",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_337.png",
    "regX": 85,
    "regY": 125
  },
  "3_338": {
    "id": "3_338",
    "name": "edificio059",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_338.png",
    "regX": 85,
    "regY": 126
  },
  "3_339": {
    "id": "3_339",
    "name": "edificio065",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_339.png",
    "regX": 70,
    "regY": 83
  },
  "3_340": {
    "id": "3_340",
    "name": "edificio066",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_340.png",
    "regX": 70,
    "regY": 91
  },
  "3_341": {
    "id": "3_341",
    "name": "edificio067",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_341.png",
    "regX": 69,
    "regY": 93
  },
  "3_342": {
    "id": "3_342",
    "name": "edificio068",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_342.png",
    "regX": 72,
    "regY": 104
  },
  "3_343": {
    "id": "3_343",
    "name": "edificio069",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_343.png",
    "regX": 73,
    "regY": 112
  },
  "3_344": {
    "id": "3_344",
    "name": "casa014",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_344.png",
    "regX": 74,
    "regY": 71
  },
  "3_345": {
    "id": "3_345",
    "name": "casa024",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_345.png",
    "regX": 64,
    "regY": 81
  },
  "3_346": {
    "id": "3_346",
    "name": "casa034",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_346.png",
    "regX": 35,
    "regY": 59
  },
  "3_347": {
    "id": "3_347",
    "name": "casa044",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_347.png",
    "regX": 48,
    "regY": 100
  },
  "3_348": {
    "id": "3_348",
    "name": "casa054",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_348.png",
    "regX": 45,
    "regY": 67
  },
  "3_349": {
    "id": "3_349",
    "name": "casa064",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/3_349.png",
    "regX": 53,
    "regY": 80
  },
  "4_17": {
    "id": "4_17",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_17.png",
    "regX": 10,
    "regY": 13
  },
  "4_18": {
    "id": "4_18",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_18.png",
    "regX": 10,
    "regY": 14
  },
  "4_19": {
    "id": "4_19",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_19.png",
    "regX": 10,
    "regY": 15
  },
  "4_20": {
    "id": "4_20",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_20.png",
    "regX": 10,
    "regY": 14
  },
  "4_21": {
    "id": "4_21",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_21.png",
    "regX": 10,
    "regY": 13
  },
  "4_22": {
    "id": "4_22",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_22.png",
    "regX": 10,
    "regY": 14
  },
  "4_23": {
    "id": "4_23",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_23.png",
    "regX": 10,
    "regY": 15
  },
  "4_24": {
    "id": "4_24",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_24.png",
    "regX": 10,
    "regY": 14
  },
  "4_25": {
    "id": "4_25",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_25.png",
    "regX": 9,
    "regY": 13
  },
  "4_26": {
    "id": "4_26",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_26.png",
    "regX": 9,
    "regY": 14
  },
  "4_27": {
    "id": "4_27",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_27.png",
    "regX": 8,
    "regY": 15
  },
  "4_28": {
    "id": "4_28",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_28.png",
    "regX": 8,
    "regY": 14
  },
  "4_29": {
    "id": "4_29",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_29.png",
    "regX": 10,
    "regY": 13
  },
  "4_30": {
    "id": "4_30",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_30.png",
    "regX": 8,
    "regY": 14
  },
  "4_31": {
    "id": "4_31",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_31.png",
    "regX": 9,
    "regY": 15
  },
  "4_32": {
    "id": "4_32",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_32.png",
    "regX": 9,
    "regY": 14
  },
  "4_33": {
    "id": "4_33",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_33.png",
    "regX": 16,
    "regY": 10
  },
  "4_34": {
    "id": "4_34",
    "name": "deadTerrorNorth",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/4_34.png",
    "regX": 16,
    "regY": 10
  },
  "5_12": {
    "id": "5_12",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_12.png",
    "regX": 7,
    "regY": 14
  },
  "5_13": {
    "id": "5_13",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_13.png",
    "regX": 5,
    "regY": 15
  },
  "5_14": {
    "id": "5_14",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_14.png",
    "regX": 4,
    "regY": 16
  },
  "5_15": {
    "id": "5_15",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_15.png",
    "regX": 6,
    "regY": 15
  },
  "5_16": {
    "id": "5_16",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_16.png",
    "regX": 9,
    "regY": 14
  },
  "5_17": {
    "id": "5_17",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_17.png",
    "regX": 5,
    "regY": 14
  },
  "5_18": {
    "id": "5_18",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_18.png",
    "regX": 4,
    "regY": 15
  },
  "5_19": {
    "id": "5_19",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_19.png",
    "regX": 5,
    "regY": 14
  },
  "5_20": {
    "id": "5_20",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_20.png",
    "regX": 9,
    "regY": 13
  },
  "5_21": {
    "id": "5_21",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_21.png",
    "regX": 8,
    "regY": 14
  },
  "5_22": {
    "id": "5_22",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_22.png",
    "regX": 7,
    "regY": 15
  },
  "5_23": {
    "id": "5_23",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_23.png",
    "regX": 9,
    "regY": 14
  },
  "5_24": {
    "id": "5_24",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_24.png",
    "regX": 10,
    "regY": 13
  },
  "5_25": {
    "id": "5_25",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_25.png",
    "regX": 8,
    "regY": 14
  },
  "5_26": {
    "id": "5_26",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_26.png",
    "regX": 6,
    "regY": 15
  },
  "5_27": {
    "id": "5_27",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_27.png",
    "regX": 7,
    "regY": 14
  },
  "5_28": {
    "id": "5_28",
    "name": "terror0002",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_28.png",
    "regX": 12,
    "regY": 16
  },
  "5_29": {
    "id": "5_29",
    "name": "terror0001",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_29.png",
    "regX": 12,
    "regY": 16
  },
  "5_30": {
    "id": "5_30",
    "name": "SouthMan0001",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_30.png",
    "regX": 12,
    "regY": 3
  },
  "5_31": {
    "id": "5_31",
    "name": "SouthMan0002",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_31.png",
    "regX": 11,
    "regY": 4
  },
  "5_32": {
    "id": "5_32",
    "name": "SouthMan0003",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_32.png",
    "regX": 11,
    "regY": 5
  },
  "5_33": {
    "id": "5_33",
    "name": "SouthMan0005",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_33.png",
    "regX": 11,
    "regY": 7
  },
  "5_34": {
    "id": "5_34",
    "name": "SouthMan0006",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_34.png",
    "regX": 12,
    "regY": 11
  },
  "5_35": {
    "id": "5_35",
    "name": "westMan0001",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_35.png",
    "regX": 11,
    "regY": 4
  },
  "5_36": {
    "id": "5_36",
    "name": "westMan0002",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_36.png",
    "regX": 10,
    "regY": 4
  },
  "5_37": {
    "id": "5_37",
    "name": "westMan0003",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_37.png",
    "regX": 11,
    "regY": 5
  },
  "5_38": {
    "id": "5_38",
    "name": "westMan0004",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_38.png",
    "regX": 11,
    "regY": 6
  },
  "5_39": {
    "id": "5_39",
    "name": "westMan0005",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_39.png",
    "regX": 10,
    "regY": 2
  },
  "5_40": {
    "id": "5_40",
    "name": "westMan0006",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_40.png",
    "regX": 10,
    "regY": 1
  },
  "5_41": {
    "id": "5_41",
    "name": "westMan0007",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_41.png",
    "regX": 11,
    "regY": 1
  },
  "5_42": {
    "id": "5_42",
    "name": "westMan0008",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_42.png",
    "regX": 10,
    "regY": 1
  },
  "5_43": {
    "id": "5_43",
    "name": "westMan0009",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_43.png",
    "regX": 11,
    "regY": 1
  },
  "5_44": {
    "id": "5_44",
    "name": "westMan0010",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_44.png",
    "regX": 10,
    "regY": 1
  },
  "5_45": {
    "id": "5_45",
    "name": "westMan0011",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_45.png",
    "regX": 10,
    "regY": 9
  },
  "5_46": {
    "id": "5_46",
    "name": "westMan0012",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_46.png",
    "regX": 9,
    "regY": 13
  },
  "5_47": {
    "id": "5_47",
    "name": "deadman",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_47.png",
    "regX": 16,
    "regY": 12
  },
  "5_48": {
    "id": "5_48",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/5_48.png",
    "regX": 16,
    "regY": 11
  },
  "6_41": {
    "id": "6_41",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_41.png",
    "regX": 8,
    "regY": 13
  },
  "6_42": {
    "id": "6_42",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_42.png",
    "regX": 7,
    "regY": 14
  },
  "6_43": {
    "id": "6_43",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_43.png",
    "regX": 6,
    "regY": 15
  },
  "6_44": {
    "id": "6_44",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_44.png",
    "regX": 5,
    "regY": 14
  },
  "6_45": {
    "id": "6_45",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_45.png",
    "regX": 9,
    "regY": 13
  },
  "6_46": {
    "id": "6_46",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_46.png",
    "regX": 6,
    "regY": 14
  },
  "6_47": {
    "id": "6_47",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_47.png",
    "regX": 6,
    "regY": 14
  },
  "6_48": {
    "id": "6_48",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_48.png",
    "regX": 7,
    "regY": 14
  },
  "6_49": {
    "id": "6_49",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_49.png",
    "regX": 8,
    "regY": 12
  },
  "6_50": {
    "id": "6_50",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_50.png",
    "regX": 7,
    "regY": 13
  },
  "6_51": {
    "id": "6_51",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_51.png",
    "regX": 7,
    "regY": 13
  },
  "6_52": {
    "id": "6_52",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_52.png",
    "regX": 8,
    "regY": 13
  },
  "6_53": {
    "id": "6_53",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_53.png",
    "regX": 9,
    "regY": 12
  },
  "6_54": {
    "id": "6_54",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_54.png",
    "regX": 8,
    "regY": 13
  },
  "6_55": {
    "id": "6_55",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_55.png",
    "regX": 6,
    "regY": 13
  },
  "6_56": {
    "id": "6_56",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_56.png",
    "regX": 7,
    "regY": 13
  },
  "6_57": {
    "id": "6_57",
    "name": "terror0002",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_57.png",
    "regX": 12,
    "regY": 16
  },
  "6_58": {
    "id": "6_58",
    "name": "terror0001",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_58.png",
    "regX": 12,
    "regY": 16
  },
  "6_59": {
    "id": "6_59",
    "name": "womanSouth0013",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_59.png",
    "regX": 7,
    "regY": 6
  },
  "6_60": {
    "id": "6_60",
    "name": "womanSouth0014",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_60.png",
    "regX": 8,
    "regY": 7
  },
  "6_61": {
    "id": "6_61",
    "name": "womanSouth0015",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_61.png",
    "regX": 7,
    "regY": 6
  },
  "6_62": {
    "id": "6_62",
    "name": "womanSouth0016",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_62.png",
    "regX": 8,
    "regY": 10
  },
  "6_63": {
    "id": "6_63",
    "name": "womanSouth0017",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_63.png",
    "regX": 8,
    "regY": 12
  },
  "6_64": {
    "id": "6_64",
    "name": "womanSouth0018",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_64.png",
    "regX": 17,
    "regY": 18
  },
  "6_65": {
    "id": "6_65",
    "name": "womanWest0001",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_65.png",
    "regX": 8,
    "regY": 5
  },
  "6_66": {
    "id": "6_66",
    "name": "womanWest0002",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_66.png",
    "regX": 7,
    "regY": 6
  },
  "6_67": {
    "id": "6_67",
    "name": "womanWest0003",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_67.png",
    "regX": 7,
    "regY": 6
  },
  "6_68": {
    "id": "6_68",
    "name": "womanWest0004",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_68.png",
    "regX": 7,
    "regY": 10
  },
  "6_69": {
    "id": "6_69",
    "name": "womanWest0005",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_69.png",
    "regX": 9,
    "regY": 10
  },
  "6_70": {
    "id": "6_70",
    "name": "womanWest0006",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_70.png",
    "regX": 12,
    "regY": 15
  },
  "6_71": {
    "id": "6_71",
    "name": "deadwoman",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_71.png",
    "regX": 17,
    "regY": 10
  },
  "6_72": {
    "id": "6_72",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/6_72.png",
    "regX": 12,
    "regY": 10
  },
  "8_1": {
    "id": "8_1",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_1.png",
    "regX": 5,
    "regY": 5
  },
  "8_2": {
    "id": "8_2",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_2.png",
    "regX": 4,
    "regY": 6
  },
  "8_3": {
    "id": "8_3",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_3.png",
    "regX": 4,
    "regY": 7
  },
  "8_4": {
    "id": "8_4",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_4.png",
    "regX": 4,
    "regY": 6
  },
  "8_5": {
    "id": "8_5",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_5.png",
    "regX": 7,
    "regY": 5
  },
  "8_6": {
    "id": "8_6",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_6.png",
    "regX": 4,
    "regY": 6
  },
  "8_7": {
    "id": "8_7",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_7.png",
    "regX": 4,
    "regY": 7
  },
  "8_8": {
    "id": "8_8",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_8.png",
    "regX": 5,
    "regY": 6
  },
  "8_9": {
    "id": "8_9",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_9.png",
    "regX": 5,
    "regY": 7
  },
  "8_10": {
    "id": "8_10",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_10.png",
    "regX": 6,
    "regY": 8
  },
  "8_11": {
    "id": "8_11",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_11.png",
    "regX": 6,
    "regY": 9
  },
  "8_12": {
    "id": "8_12",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_12.png",
    "regX": 5,
    "regY": 8
  },
  "8_13": {
    "id": "8_13",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_13.png",
    "regX": 8,
    "regY": 7
  },
  "8_14": {
    "id": "8_14",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_14.png",
    "regX": 6,
    "regY": 8
  },
  "8_15": {
    "id": "8_15",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_15.png",
    "regX": 5,
    "regY": 9
  },
  "8_16": {
    "id": "8_16",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_16.png",
    "regX": 6,
    "regY": 8
  },
  "8_17": {
    "id": "8_17",
    "name": "deadkid",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_17.png",
    "regX": 12,
    "regY": 8
  },
  "8_18": {
    "id": "8_18",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_18.png",
    "regX": 11,
    "regY": 10
  },
  "8_19": {
    "id": "8_19",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_19.png",
    "regX": 6,
    "regY": 1
  },
  "8_20": {
    "id": "8_20",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_20.png",
    "regX": 5,
    "regY": 2
  },
  "8_21": {
    "id": "8_21",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_21.png",
    "regX": 5,
    "regY": 2
  },
  "8_22": {
    "id": "8_22",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_22.png",
    "regX": 5,
    "regY": 2
  },
  "8_23": {
    "id": "8_23",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_23.png",
    "regX": 5,
    "regY": 0
  },
  "8_24": {
    "id": "8_24",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_24.png",
    "regX": 5,
    "regY": 0
  },
  "8_25": {
    "id": "8_25",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_25.png",
    "regX": 5,
    "regY": 1
  },
  "8_26": {
    "id": "8_26",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_26.png",
    "regX": 5,
    "regY": 1
  },
  "8_27": {
    "id": "8_27",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_27.png",
    "regX": 5,
    "regY": 1
  },
  "8_28": {
    "id": "8_28",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_28.png",
    "regX": 8,
    "regY": 7
  },
  "8_29": {
    "id": "8_29",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_29.png",
    "regX": 12,
    "regY": 9
  },
  "8_30": {
    "id": "8_30",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_30.png",
    "regX": 6,
    "regY": 2
  },
  "8_31": {
    "id": "8_31",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_31.png",
    "regX": 6,
    "regY": 2
  },
  "8_32": {
    "id": "8_32",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_32.png",
    "regX": 6,
    "regY": 2
  },
  "8_33": {
    "id": "8_33",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_33.png",
    "regX": 12,
    "regY": 0
  },
  "8_34": {
    "id": "8_34",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_34.png",
    "regX": 12,
    "regY": -4
  },
  "8_35": {
    "id": "8_35",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_35.png",
    "regX": 12,
    "regY": -3
  },
  "8_36": {
    "id": "8_36",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_36.png",
    "regX": 12,
    "regY": -3
  },
  "8_37": {
    "id": "8_37",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_37.png",
    "regX": 12,
    "regY": -4
  },
  "8_38": {
    "id": "8_38",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_38.png",
    "regX": 12,
    "regY": -3
  },
  "8_39": {
    "id": "8_39",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_39.png",
    "regX": 9,
    "regY": 0
  },
  "8_40": {
    "id": "8_40",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_40.png",
    "regX": 6,
    "regY": 6
  },
  "8_41": {
    "id": "8_41",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_41.png",
    "regX": 7,
    "regY": 12
  },
  "8_42": {
    "id": "8_42",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_42.png",
    "regX": 6,
    "regY": 1
  },
  "8_43": {
    "id": "8_43",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_43.png",
    "regX": 5,
    "regY": 2
  },
  "8_44": {
    "id": "8_44",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_44.png",
    "regX": 5,
    "regY": 2
  },
  "8_45": {
    "id": "8_45",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_45.png",
    "regX": 5,
    "regY": 2
  },
  "8_46": {
    "id": "8_46",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_46.png",
    "regX": 5,
    "regY": 0
  },
  "8_47": {
    "id": "8_47",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_47.png",
    "regX": 5,
    "regY": 0
  },
  "8_48": {
    "id": "8_48",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_48.png",
    "regX": 5,
    "regY": 1
  },
  "8_49": {
    "id": "8_49",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_49.png",
    "regX": 5,
    "regY": 1
  },
  "8_50": {
    "id": "8_50",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_50.png",
    "regX": 5,
    "regY": 1
  },
  "8_51": {
    "id": "8_51",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_51.png",
    "regX": 3,
    "regY": 7
  },
  "8_52": {
    "id": "8_52",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_52.png",
    "regX": 5,
    "regY": 9
  },
  "8_53": {
    "id": "8_53",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_53.png",
    "regX": 6,
    "regY": 2
  },
  "8_54": {
    "id": "8_54",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_54.png",
    "regX": 6,
    "regY": 2
  },
  "8_55": {
    "id": "8_55",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_55.png",
    "regX": 6,
    "regY": 2
  },
  "8_56": {
    "id": "8_56",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_56.png",
    "regX": 12,
    "regY": 0
  },
  "8_57": {
    "id": "8_57",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_57.png",
    "regX": 12,
    "regY": -4
  },
  "8_58": {
    "id": "8_58",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_58.png",
    "regX": 12,
    "regY": -3
  },
  "8_59": {
    "id": "8_59",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_59.png",
    "regX": 12,
    "regY": -3
  },
  "8_60": {
    "id": "8_60",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_60.png",
    "regX": 12,
    "regY": -4
  },
  "8_61": {
    "id": "8_61",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_61.png",
    "regX": 11,
    "regY": -3
  },
  "8_62": {
    "id": "8_62",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_62.png",
    "regX": 9,
    "regY": 0
  },
  "8_63": {
    "id": "8_63",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_63.png",
    "regX": 12,
    "regY": 5
  },
  "8_64": {
    "id": "8_64",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_64.png",
    "regX": 12,
    "regY": 10
  },
  "8_66": {
    "id": "8_66",
    "name": "terror0002",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_66.png",
    "regX": 12,
    "regY": 16
  },
  "8_67": {
    "id": "8_67",
    "name": "terror0001",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/8_67.png",
    "regX": 12,
    "regY": 16
  },
  "9_1": {
    "id": "9_1",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_1.png",
    "regX": 10,
    "regY": 4
  },
  "9_2": {
    "id": "9_2",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_2.png",
    "regX": 10,
    "regY": 4
  },
  "9_3": {
    "id": "9_3",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_3.png",
    "regX": 10,
    "regY": 1
  },
  "9_4": {
    "id": "9_4",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_4.png",
    "regX": 10,
    "regY": 3
  },
  "9_5": {
    "id": "9_5",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_5.png",
    "regX": 10,
    "regY": 3
  },
  "9_6": {
    "id": "9_6",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_6.png",
    "regX": 10,
    "regY": 4
  },
  "9_7": {
    "id": "9_7",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_7.png",
    "regX": 10,
    "regY": 3
  },
  "9_8": {
    "id": "9_8",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_8.png",
    "regX": 10,
    "regY": 5
  },
  "9_9": {
    "id": "9_9",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_9.png",
    "regX": 8,
    "regY": 0
  },
  "9_10": {
    "id": "9_10",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_10.png",
    "regX": 8,
    "regY": 0
  },
  "9_11": {
    "id": "9_11",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_11.png",
    "regX": 8,
    "regY": 1
  },
  "9_12": {
    "id": "9_12",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_12.png",
    "regX": 8,
    "regY": 0
  },
  "9_13": {
    "id": "9_13",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_13.png",
    "regX": 10,
    "regY": 0
  },
  "9_14": {
    "id": "9_14",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_14.png",
    "regX": 8,
    "regY": 0
  },
  "9_15": {
    "id": "9_15",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_15.png",
    "regX": 8,
    "regY": 1
  },
  "9_16": {
    "id": "9_16",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_16.png",
    "regX": 8,
    "regY": 0
  },
  "9_17": {
    "id": "9_17",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_17.png",
    "regX": 9,
    "regY": 6
  },
  "9_18": {
    "id": "9_18",
    "name": "copy",
    "src": "/sept12%20for%20vibe/Sept12assets/sep12/9_18.png",
    "regX": 9,
    "regY": 6
  }
};
