import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'

const saveMapPlugin = () => ({
  name: 'save-map-plugin',
  configureServer(server) {
    server.middlewares.use((req, res, next) => {
      if (req.url === '/api/save-map' && req.method === 'POST') {
        let body = ''
        req.on('data', chunk => {
          body += chunk.toString()
        })
        req.on('end', () => {
          try {
            const data = JSON.parse(body)
            const filePath = path.resolve(__dirname, 'src/game/mapData.js')
            const content = `// Auto-generated by PlacementTool\nexport const MAP_PLACEMENTS = ${JSON.stringify(data, null, 4)};\n`
            fs.writeFileSync(filePath, content)

            res.statusCode = 200
            res.end(JSON.stringify({ success: true }))
          } catch (e) {
            console.error('Error saving map:', e)
            res.statusCode = 500
            res.end(JSON.stringify({ error: e.message }))
          }
        })
      } else {
        next()
      }
    })
  }
})

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), saveMapPlugin()],
})
